#pragma once

namespace Components
{
	struct WeaponField
	{
		const char* name;
		std::size_t offset;
		int type;
	};

	static constexpr WeaponField weaponFields[] =
	{
		{ "displayName", offsetof(Game::WeaponFullDef, complete.szDisplayName), 0 },
		{ "AIOverlayDescription", offsetof(Game::WeaponFullDef, weapDef.szOverlayName), 0 },
		{ "modeName", offsetof(Game::WeaponFullDef, weapDef.szModeName), 0 },
		{ "playerAnimType", offsetof(Game::WeaponFullDef, weapDef.playerAnimType), 24 },
		{ "gunModel", offsetof(Game::WeaponFullDef, gunXModel[0]), 11 },
		{ "gunModel2", offsetof(Game::WeaponFullDef, gunXModel[1]), 11 },
		{ "gunModel3", offsetof(Game::WeaponFullDef, gunXModel[2]), 11 },
		{ "gunModel4", offsetof(Game::WeaponFullDef, gunXModel[3]), 11 },
		{ "gunModel5", offsetof(Game::WeaponFullDef, gunXModel[4]), 11 },
		{ "gunModel6", offsetof(Game::WeaponFullDef, gunXModel[5]), 11 },
		{ "gunModel7", offsetof(Game::WeaponFullDef, gunXModel[6]), 11 },
		{ "gunModel8", offsetof(Game::WeaponFullDef, gunXModel[7]), 11 },
		{ "gunModel9", offsetof(Game::WeaponFullDef, gunXModel[8]), 11 },
		{ "gunModel10", offsetof(Game::WeaponFullDef, gunXModel[9]), 11 },
		{ "gunModel11", offsetof(Game::WeaponFullDef, gunXModel[10]), 11 },
		{ "gunModel12", offsetof(Game::WeaponFullDef, gunXModel[11]), 11 },
		{ "gunModel13", offsetof(Game::WeaponFullDef, gunXModel[12]), 11 },
		{ "gunModel14", offsetof(Game::WeaponFullDef, gunXModel[13]), 11 },
		{ "gunModel15", offsetof(Game::WeaponFullDef, gunXModel[14]), 11 },
		{ "gunModel16", offsetof(Game::WeaponFullDef, gunXModel[15]), 11 },
		{ "handModel", offsetof(Game::WeaponFullDef, weapDef.handXModel), 11 },
		{ "hideTags", offsetof(Game::WeaponFullDef, hideTags[0]), 38 },
		{ "notetrackSoundMap", offsetof(Game::WeaponFullDef, notetrackSoundMapKeys[0]), 39 },
		{ "notetrackRumbleMap", offsetof(Game::WeaponFullDef, notetrackRumbleMapKeys[0]), 40 },
		{ "idleAnim", offsetof(Game::WeaponFullDef, szXAnims[1]), 0 },
		{ "emptyIdleAnim", offsetof(Game::WeaponFullDef, szXAnims[2]), 0 },
		{ "fireAnim", offsetof(Game::WeaponFullDef, szXAnims[3]), 0 },
		{ "holdFireAnim", offsetof(Game::WeaponFullDef, szXAnims[4]), 0 },
		{ "lastShotAnim", offsetof(Game::WeaponFullDef, szXAnims[5]), 0 },
		{ "detonateAnim", offsetof(Game::WeaponFullDef, szXAnims[29]), 0 },
		{ "rechamberAnim", offsetof(Game::WeaponFullDef, szXAnims[6]), 0 },
		{ "meleeAnim", offsetof(Game::WeaponFullDef, szXAnims[7]), 0 },
		{ "meleeChargeAnim", offsetof(Game::WeaponFullDef, szXAnims[8]), 0 },
		{ "reloadAnim", offsetof(Game::WeaponFullDef, szXAnims[9]), 0 },
		{ "reloadEmptyAnim", offsetof(Game::WeaponFullDef, szXAnims[10]), 0 },
		{ "reloadStartAnim", offsetof(Game::WeaponFullDef, szXAnims[11]), 0 },
		{ "reloadEndAnim", offsetof(Game::WeaponFullDef, szXAnims[12]), 0 },
		{ "raiseAnim", offsetof(Game::WeaponFullDef, szXAnims[13]), 0 },
		{ "dropAnim", offsetof(Game::WeaponFullDef, szXAnims[16]), 0 },
		{ "firstRaiseAnim", offsetof(Game::WeaponFullDef, szXAnims[14]), 0 },
		{ "breachRaiseAnim", offsetof(Game::WeaponFullDef, szXAnims[15]), 0 },
		{ "altRaiseAnim", offsetof(Game::WeaponFullDef, szXAnims[17]), 0 },
		{ "altDropAnim", offsetof(Game::WeaponFullDef, szXAnims[18]), 0 },
		{ "quickRaiseAnim", offsetof(Game::WeaponFullDef, szXAnims[19]), 0 },
		{ "quickDropAnim", offsetof(Game::WeaponFullDef, szXAnims[20]), 0 },
		{ "emptyRaiseAnim", offsetof(Game::WeaponFullDef, szXAnims[21]), 0 },
		{ "emptyDropAnim", offsetof(Game::WeaponFullDef, szXAnims[22]), 0 },
		{ "sprintInAnim", offsetof(Game::WeaponFullDef, szXAnims[23]), 0 },
		{ "sprintLoopAnim", offsetof(Game::WeaponFullDef, szXAnims[24]), 0 },
		{ "sprintOutAnim", offsetof(Game::WeaponFullDef, szXAnims[25]), 0 },
		{ "stunnedAnimStart", offsetof(Game::WeaponFullDef, szXAnims[26]), 0 },
		{ "stunnedAnimLoop", offsetof(Game::WeaponFullDef, szXAnims[27]), 0 },
		{ "stunnedAnimEnd", offsetof(Game::WeaponFullDef, szXAnims[28]), 0 },
		{ "nightVisionWearAnim", offsetof(Game::WeaponFullDef, szXAnims[30]), 0 },
		{ "nightVisionRemoveAnim", offsetof(Game::WeaponFullDef, szXAnims[31]), 0 },
		{ "adsFireAnim", offsetof(Game::WeaponFullDef, szXAnims[32]), 0 },
		{ "adsLastShotAnim", offsetof(Game::WeaponFullDef, szXAnims[33]), 0 },
		{ "adsRechamberAnim", offsetof(Game::WeaponFullDef, szXAnims[34]), 0 },
		{ "adsUpAnim", offsetof(Game::WeaponFullDef, szXAnims[35]), 0 },
		{ "adsDownAnim", offsetof(Game::WeaponFullDef, szXAnims[36]), 0 },
		{ "idleAnimR", offsetof(Game::WeaponFullDef, szXAnimsRightHanded[1]), 0 },
		{ "emptyIdleAnimR", offsetof(Game::WeaponFullDef, szXAnimsRightHanded[2]), 0 },
		{ "fireAnimR", offsetof(Game::WeaponFullDef, szXAnimsRightHanded[3]), 0 },
		{ "holdFireAnimR", offsetof(Game::WeaponFullDef, szXAnimsRightHanded[4]), 0 },
		{ "lastShotAnimR", offsetof(Game::WeaponFullDef, szXAnimsRightHanded[5]), 0 },
		{ "detonateAnimR", offsetof(Game::WeaponFullDef, szXAnimsRightHanded[29]), 0 },
		{ "rechamberAnimR", offsetof(Game::WeaponFullDef, szXAnimsRightHanded[6]), 0 },
		{ "meleeAnimR", offsetof(Game::WeaponFullDef, szXAnimsRightHanded[7]), 0 },
		{ "meleeChargeAnimR", offsetof(Game::WeaponFullDef, szXAnimsRightHanded[8]), 0 },
		{ "reloadAnimR", offsetof(Game::WeaponFullDef, szXAnimsRightHanded[9]), 0 },
		{ "reloadEmptyAnimR", offsetof(Game::WeaponFullDef, szXAnimsRightHanded[10]), 0 },
		{ "reloadStartAnimR", offsetof(Game::WeaponFullDef, szXAnimsRightHanded[11]), 0 },
		{ "reloadEndAnimR", offsetof(Game::WeaponFullDef, szXAnimsRightHanded[12]), 0 },
		{ "raiseAnimR", offsetof(Game::WeaponFullDef, szXAnimsRightHanded[13]), 0 },
		{ "dropAnimR", offsetof(Game::WeaponFullDef, szXAnimsRightHanded[16]), 0 },
		{ "firstRaiseAnimR", offsetof(Game::WeaponFullDef, szXAnimsRightHanded[14]), 0 },
		{ "breachRaiseAnimR", offsetof(Game::WeaponFullDef, szXAnimsRightHanded[15]), 0 },
		{ "altRaiseAnimR", offsetof(Game::WeaponFullDef, szXAnimsRightHanded[17]), 0 },
		{ "altDropAnimR", offsetof(Game::WeaponFullDef, szXAnimsRightHanded[18]), 0 },
		{ "quickRaiseAnimR", offsetof(Game::WeaponFullDef, szXAnimsRightHanded[19]), 0 },
		{ "quickDropAnimR", offsetof(Game::WeaponFullDef, szXAnimsRightHanded[20]), 0 },
		{ "emptyRaiseAnimR", offsetof(Game::WeaponFullDef, szXAnimsRightHanded[21]), 0 },
		{ "emptyDropAnimR", offsetof(Game::WeaponFullDef, szXAnimsRightHanded[22]), 0 },
		{ "sprintInAnimR", offsetof(Game::WeaponFullDef, szXAnimsRightHanded[23]), 0 },
		{ "sprintLoopAnimR", offsetof(Game::WeaponFullDef, szXAnimsRightHanded[24]), 0 },
		{ "sprintOutAnimR", offsetof(Game::WeaponFullDef, szXAnimsRightHanded[25]), 0 },
		{ "stunnedAnimStartR", offsetof(Game::WeaponFullDef, szXAnimsRightHanded[26]), 0 },
		{ "stunnedAnimLoopR", offsetof(Game::WeaponFullDef, szXAnimsRightHanded[27]), 0 },
		{ "stunnedAnimEndR", offsetof(Game::WeaponFullDef, szXAnimsRightHanded[28]), 0 },
		{ "nightVisionWearAnimR", offsetof(Game::WeaponFullDef, szXAnimsRightHanded[30]), 0 },
		{ "nightVisionRemoveAnimR", offsetof(Game::WeaponFullDef, szXAnimsRightHanded[31]), 0 },
		{ "adsFireAnimR", offsetof(Game::WeaponFullDef, szXAnimsRightHanded[32]), 0 },
		{ "adsLastShotAnimR", offsetof(Game::WeaponFullDef, szXAnimsRightHanded[33]), 0 },
		{ "adsRechamberAnimR", offsetof(Game::WeaponFullDef, szXAnimsRightHanded[34]), 0 },
		{ "adsUpAnimR", offsetof(Game::WeaponFullDef, szXAnimsRightHanded[35]), 0 },
		{ "adsDownAnimR", offsetof(Game::WeaponFullDef, szXAnimsRightHanded[36]), 0 },
		{ "idleAnimL", offsetof(Game::WeaponFullDef, szXAnimsLeftHanded[1]), 0 },
		{ "emptyIdleAnimL", offsetof(Game::WeaponFullDef, szXAnimsLeftHanded[2]), 0 },
		{ "fireAnimL", offsetof(Game::WeaponFullDef, szXAnimsLeftHanded[3]), 0 },
		{ "holdFireAnimL", offsetof(Game::WeaponFullDef, szXAnimsLeftHanded[4]), 0 },
		{ "lastShotAnimL", offsetof(Game::WeaponFullDef, szXAnimsLeftHanded[5]), 0 },
		{ "detonateAnimL", offsetof(Game::WeaponFullDef, szXAnimsLeftHanded[29]), 0 },
		{ "rechamberAnimL", offsetof(Game::WeaponFullDef, szXAnimsLeftHanded[6]), 0 },
		{ "meleeAnimL", offsetof(Game::WeaponFullDef, szXAnimsLeftHanded[7]), 0 },
		{ "meleeChargeAnimL", offsetof(Game::WeaponFullDef, szXAnimsLeftHanded[8]), 0 },
		{ "reloadAnimL", offsetof(Game::WeaponFullDef, szXAnimsLeftHanded[9]), 0 },
		{ "reloadEmptyAnimL", offsetof(Game::WeaponFullDef, szXAnimsLeftHanded[10]), 0 },
		{ "reloadStartAnimL", offsetof(Game::WeaponFullDef, szXAnimsLeftHanded[11]), 0 },
		{ "reloadEndAnimL", offsetof(Game::WeaponFullDef, szXAnimsLeftHanded[12]), 0 },
		{ "raiseAnimL", offsetof(Game::WeaponFullDef, szXAnimsLeftHanded[13]), 0 },
		{ "dropAnimL", offsetof(Game::WeaponFullDef, szXAnimsLeftHanded[16]), 0 },
		{ "firstRaiseAnimL", offsetof(Game::WeaponFullDef, szXAnimsLeftHanded[14]), 0 },
		{ "breachRaiseAnimL", offsetof(Game::WeaponFullDef, szXAnimsLeftHanded[15]), 0 },
		{ "altRaiseAnimL", offsetof(Game::WeaponFullDef, szXAnimsLeftHanded[17]), 0 },
		{ "altDropAnimL", offsetof(Game::WeaponFullDef, szXAnimsLeftHanded[18]), 0 },
		{ "quickRaiseAnimL", offsetof(Game::WeaponFullDef, szXAnimsLeftHanded[19]), 0 },
		{ "quickDropAnimL", offsetof(Game::WeaponFullDef, szXAnimsLeftHanded[20]), 0 },
		{ "emptyRaiseAnimL", offsetof(Game::WeaponFullDef, szXAnimsLeftHanded[21]), 0 },
		{ "emptyDropAnimL", offsetof(Game::WeaponFullDef, szXAnimsLeftHanded[22]), 0 },
		{ "sprintInAnimL", offsetof(Game::WeaponFullDef, szXAnimsLeftHanded[23]), 0 },
		{ "sprintLoopAnimL", offsetof(Game::WeaponFullDef, szXAnimsLeftHanded[24]), 0 },
		{ "sprintOutAnimL", offsetof(Game::WeaponFullDef, szXAnimsLeftHanded[25]), 0 },
		{ "stunnedAnimStartL", offsetof(Game::WeaponFullDef, szXAnimsLeftHanded[26]), 0 },
		{ "stunnedAnimLoopL", offsetof(Game::WeaponFullDef, szXAnimsLeftHanded[27]), 0 },
		{ "stunnedAnimEndL", offsetof(Game::WeaponFullDef, szXAnimsLeftHanded[28]), 0 },
		{ "nightVisionWearAnimL", offsetof(Game::WeaponFullDef, szXAnimsLeftHanded[30]), 0 },
		{ "nightVisionRemoveAnimL", offsetof(Game::WeaponFullDef, szXAnimsLeftHanded[31]), 0 },
		{ "adsFireAnimL", offsetof(Game::WeaponFullDef, szXAnimsLeftHanded[32]), 0 },
		{ "adsLastShotAnimL", offsetof(Game::WeaponFullDef, szXAnimsLeftHanded[33]), 0 },
		{ "adsRechamberAnimL", offsetof(Game::WeaponFullDef, szXAnimsLeftHanded[34]), 0 },
		{ "adsUpAnimL", offsetof(Game::WeaponFullDef, szXAnimsLeftHanded[35]), 0 },
		{ "adsDownAnimL", offsetof(Game::WeaponFullDef, szXAnimsLeftHanded[36]), 0 },
		{ "script", offsetof(Game::WeaponFullDef, weapDef.szScript), 0 },
		{ "weaponType", offsetof(Game::WeaponFullDef, weapDef.weapType), 16 },
		{ "weaponClass", offsetof(Game::WeaponFullDef, weapDef.weapClass), 17 },
		{ "penetrateType", offsetof(Game::WeaponFullDef, weapDef.penetrateType), 19 },
		{ "penetrateMultiplier", offsetof(Game::WeaponFullDef, complete.penetrateMultiplier), 7 },
		{ "impactType", offsetof(Game::WeaponFullDef, complete.impactType), 20 },
		{ "inventoryType", offsetof(Game::WeaponFullDef, weapDef.inventoryType), 30 },
		{ "fireType", offsetof(Game::WeaponFullDef, weapDef.fireType), 31 },
		{ "offhandClass", offsetof(Game::WeaponFullDef, weapDef.offhandClass), 23 },
		{ "viewFlashEffect", offsetof(Game::WeaponFullDef, weapDef.viewFlashEffect), 10 },
		{ "worldFlashEffect", offsetof(Game::WeaponFullDef, weapDef.worldFlashEffect), 10 },
		{ "pickupSound", offsetof(Game::WeaponFullDef, weapDef.pickupSound), 14 },
		{ "pickupSoundPlayer", offsetof(Game::WeaponFullDef, weapDef.pickupSoundPlayer), 14 },
		{ "ammoPickupSound", offsetof(Game::WeaponFullDef, weapDef.ammoPickupSound), 14 },
		{ "ammoPickupSoundPlayer", offsetof(Game::WeaponFullDef, weapDef.ammoPickupSoundPlayer), 14 },
		{ "projectileSound", offsetof(Game::WeaponFullDef, weapDef.projectileSound), 14 },
		{ "pullbackSound", offsetof(Game::WeaponFullDef, weapDef.pullbackSound), 14 },
		{ "pullbackSoundPlayer", offsetof(Game::WeaponFullDef, weapDef.pullbackSoundPlayer), 14 },
		{ "fireSound", offsetof(Game::WeaponFullDef, weapDef.fireSound), 14 },
		{ "fireSoundPlayer", offsetof(Game::WeaponFullDef, weapDef.fireSoundPlayer), 14 },
		{ "fireSoundPlayerAkimbo", offsetof(Game::WeaponFullDef, weapDef.fireSoundPlayerAkimbo), 14 },
		{ "loopFireSound", offsetof(Game::WeaponFullDef, weapDef.fireLoopSound), 14 },
		{ "loopFireSoundPlayer", offsetof(Game::WeaponFullDef, weapDef.fireLoopSoundPlayer), 14 },
		{ "stopFireSound", offsetof(Game::WeaponFullDef, weapDef.fireStopSound), 14 },
		{ "stopFireSoundPlayer", offsetof(Game::WeaponFullDef, weapDef.fireStopSoundPlayer), 14 },
		{ "lastShotSound", offsetof(Game::WeaponFullDef, weapDef.fireLastSound), 14 },
		{ "lastShotSoundPlayer", offsetof(Game::WeaponFullDef, weapDef.fireLastSoundPlayer), 14 },
		{ "emptyFireSound", offsetof(Game::WeaponFullDef, weapDef.emptyFireSound), 14 },
		{ "emptyFireSoundPlayer", offsetof(Game::WeaponFullDef, weapDef.emptyFireSoundPlayer), 14 },
		{ "meleeSwipeSound", offsetof(Game::WeaponFullDef, weapDef.meleeSwipeSound), 14 },
		{ "meleeSwipeSoundPlayer", offsetof(Game::WeaponFullDef, weapDef.meleeSwipeSoundPlayer), 14 },
		{ "meleeHitSound", offsetof(Game::WeaponFullDef, weapDef.meleeHitSound), 14 },
		{ "meleeMissSound", offsetof(Game::WeaponFullDef, weapDef.meleeMissSound), 14 },
		{ "rechamberSound", offsetof(Game::WeaponFullDef, weapDef.rechamberSound), 14 },
		{ "rechamberSoundPlayer", offsetof(Game::WeaponFullDef, weapDef.rechamberSoundPlayer), 14 },
		{ "reloadSound", offsetof(Game::WeaponFullDef, weapDef.reloadSound), 14 },
		{ "reloadSoundPlayer", offsetof(Game::WeaponFullDef, weapDef.reloadSoundPlayer), 14 },
		{ "reloadEmptySound", offsetof(Game::WeaponFullDef, weapDef.reloadEmptySound), 14 },
		{ "reloadEmptySoundPlayer", offsetof(Game::WeaponFullDef, weapDef.reloadEmptySoundPlayer), 14 },
		{ "reloadStartSound", offsetof(Game::WeaponFullDef, weapDef.reloadStartSound), 14 },
		{ "reloadStartSoundPlayer", offsetof(Game::WeaponFullDef, weapDef.reloadStartSoundPlayer), 14 },
		{ "reloadEndSound", offsetof(Game::WeaponFullDef, weapDef.reloadEndSound), 14 },
		{ "reloadEndSoundPlayer", offsetof(Game::WeaponFullDef, weapDef.reloadEndSoundPlayer), 14 },
		{ "detonateSound", offsetof(Game::WeaponFullDef, weapDef.detonateSound), 14 },
		{ "detonateSoundPlayer", offsetof(Game::WeaponFullDef, weapDef.detonateSoundPlayer), 14 },
		{ "nightVisionWearSound", offsetof(Game::WeaponFullDef, weapDef.nightVisionWearSound), 14 },
		{ "nightVisionWearSoundPlayer", offsetof(Game::WeaponFullDef, weapDef.nightVisionWearSoundPlayer), 14 },
		{ "nightVisionRemoveSound", offsetof(Game::WeaponFullDef, weapDef.nightVisionRemoveSound), 14 },
		{ "nightVisionRemoveSoundPlayer", offsetof(Game::WeaponFullDef, weapDef.nightVisionRemoveSoundPlayer), 14 },
		{ "raiseSound", offsetof(Game::WeaponFullDef, weapDef.raiseSound), 14 },
		{ "raiseSoundPlayer", offsetof(Game::WeaponFullDef, weapDef.raiseSoundPlayer), 14 },
		{ "firstRaiseSound", offsetof(Game::WeaponFullDef, weapDef.firstRaiseSound), 14 },
		{ "firstRaiseSoundPlayer", offsetof(Game::WeaponFullDef, weapDef.firstRaiseSoundPlayer), 14 },
		{ "altSwitchSound", offsetof(Game::WeaponFullDef, weapDef.altSwitchSound), 14 },
		{ "altSwitchSoundPlayer", offsetof(Game::WeaponFullDef, weapDef.altSwitchSoundPlayer), 14 },
		{ "putawaySound", offsetof(Game::WeaponFullDef, weapDef.putawaySound), 14 },
		{ "putawaySoundPlayer", offsetof(Game::WeaponFullDef, weapDef.putawaySoundPlayer), 14 },
		{ "scanSound", offsetof(Game::WeaponFullDef, weapDef.scanSound), 14 },
		{ "bounceSound", offsetof(Game::WeaponFullDef, weapDef.bounceSound), 27 },
		{ "viewShellEjectEffect", offsetof(Game::WeaponFullDef, weapDef.viewShellEjectEffect), 10 },
		{ "worldShellEjectEffect", offsetof(Game::WeaponFullDef, weapDef.worldShellEjectEffect), 10 },
		{ "viewLastShotEjectEffect", offsetof(Game::WeaponFullDef, weapDef.viewLastShotEjectEffect), 10 },
		{ "worldLastShotEjectEffect", offsetof(Game::WeaponFullDef, weapDef.worldLastShotEjectEffect), 10 },
		{ "reticleCenter", offsetof(Game::WeaponFullDef, weapDef.reticleCenter), 12 },
		{ "reticleSide", offsetof(Game::WeaponFullDef, weapDef.reticleSide), 12 },
		{ "reticleCenterSize", offsetof(Game::WeaponFullDef, weapDef.iReticleCenterSize), 4 },
		{ "reticleSideSize", offsetof(Game::WeaponFullDef, weapDef.iReticleSideSize), 4 },
		{ "reticleMinOfs", offsetof(Game::WeaponFullDef, weapDef.iReticleMinOfs), 4 },
		{ "activeReticleType", offsetof(Game::WeaponFullDef, weapDef.activeReticleType), 25 },
		{ "standMoveF", offsetof(Game::WeaponFullDef, weapDef.vStandMove[0]), 7 },
		{ "standMoveR", offsetof(Game::WeaponFullDef, weapDef.vStandMove[1]), 7 },
		{ "standMoveU", offsetof(Game::WeaponFullDef, weapDef.vStandMove[2]), 7 },
		{ "standRotP", offsetof(Game::WeaponFullDef, weapDef.vStandRot[0]), 7 },
		{ "standRotY", offsetof(Game::WeaponFullDef, weapDef.vStandRot[1]), 7 },
		{ "standRotR", offsetof(Game::WeaponFullDef, weapDef.vStandRot[2]), 7 },
		{ "strafeMoveF", offsetof(Game::WeaponFullDef, weapDef.strafeMove[0]), 7 },
		{ "strafeMoveR", offsetof(Game::WeaponFullDef, weapDef.strafeMove[1]), 7 },
		{ "strafeMoveU", offsetof(Game::WeaponFullDef, weapDef.strafeMove[2]), 7 },
		{ "strafeRotP", offsetof(Game::WeaponFullDef, weapDef.strafeRot[0]), 7 },
		{ "strafeRotY", offsetof(Game::WeaponFullDef, weapDef.strafeRot[1]), 7 },
		{ "strafeRotR", offsetof(Game::WeaponFullDef, weapDef.strafeRot[2]), 7 },
		{ "duckedOfsF", offsetof(Game::WeaponFullDef, weapDef.vDuckedOfs[0]), 7 },
		{ "duckedOfsR", offsetof(Game::WeaponFullDef, weapDef.vDuckedOfs[1]), 7 },
		{ "duckedOfsU", offsetof(Game::WeaponFullDef, weapDef.vDuckedOfs[2]), 7 },
		{ "duckedMoveF", offsetof(Game::WeaponFullDef, weapDef.vDuckedMove[0]), 7 },
		{ "duckedMoveR", offsetof(Game::WeaponFullDef, weapDef.vDuckedMove[1]), 7 },
		{ "duckedMoveU", offsetof(Game::WeaponFullDef, weapDef.vDuckedMove[2]), 7 },
		{ "duckedRotP", offsetof(Game::WeaponFullDef, weapDef.vDuckedRot[0]), 7 },
		{ "duckedRotY", offsetof(Game::WeaponFullDef, weapDef.vDuckedRot[1]), 7 },
		{ "duckedRotR", offsetof(Game::WeaponFullDef, weapDef.vDuckedRot[2]), 7 },
		{ "proneOfsF", offsetof(Game::WeaponFullDef, weapDef.vProneOfs[0]), 7 },
		{ "proneOfsR", offsetof(Game::WeaponFullDef, weapDef.vProneOfs[1]), 7 },
		{ "proneOfsU", offsetof(Game::WeaponFullDef, weapDef.vProneOfs[2]), 7 },
		{ "proneMoveF", offsetof(Game::WeaponFullDef, weapDef.vProneMove[0]), 7 },
		{ "proneMoveR", offsetof(Game::WeaponFullDef, weapDef.vProneMove[1]), 7 },
		{ "proneMoveU", offsetof(Game::WeaponFullDef, weapDef.vProneMove[2]), 7 },
		{ "proneRotP", offsetof(Game::WeaponFullDef, weapDef.vProneRot[0]), 7 },
		{ "proneRotY", offsetof(Game::WeaponFullDef, weapDef.vProneRot[1]), 7 },
		{ "proneRotR", offsetof(Game::WeaponFullDef, weapDef.vProneRot[2]), 7 },
		{ "posMoveRate", offsetof(Game::WeaponFullDef, weapDef.fPosMoveRate), 7 },
		{ "posProneMoveRate", offsetof(Game::WeaponFullDef, weapDef.fPosProneMoveRate), 7 },
		{ "standMoveMinSpeed", offsetof(Game::WeaponFullDef, weapDef.fStandMoveMinSpeed), 7 },
		{ "duckedMoveMinSpeed", offsetof(Game::WeaponFullDef, weapDef.fDuckedMoveMinSpeed), 7 },
		{ "proneMoveMinSpeed", offsetof(Game::WeaponFullDef, weapDef.fProneMoveMinSpeed), 7 },
		{ "posRotRate", offsetof(Game::WeaponFullDef, weapDef.fPosRotRate), 7 },
		{ "posProneRotRate", offsetof(Game::WeaponFullDef, weapDef.fPosProneRotRate), 7 },
		{ "standRotMinSpeed", offsetof(Game::WeaponFullDef, weapDef.fStandRotMinSpeed), 7 },
		{ "duckedRotMinSpeed", offsetof(Game::WeaponFullDef, weapDef.fDuckedRotMinSpeed), 7 },
		{ "proneRotMinSpeed", offsetof(Game::WeaponFullDef, weapDef.fProneRotMinSpeed), 7 },
		{ "worldModel", offsetof(Game::WeaponFullDef, worldModel[0]), 11 },
		{ "worldModel2", offsetof(Game::WeaponFullDef, worldModel[1]), 11 },
		{ "worldModel3", offsetof(Game::WeaponFullDef, worldModel[2]), 11 },
		{ "worldModel4", offsetof(Game::WeaponFullDef, worldModel[3]), 11 },
		{ "worldModel5", offsetof(Game::WeaponFullDef, worldModel[4]), 11 },
		{ "worldModel6", offsetof(Game::WeaponFullDef, worldModel[5]), 11 },
		{ "worldModel7", offsetof(Game::WeaponFullDef, worldModel[6]), 11 },
		{ "worldModel8", offsetof(Game::WeaponFullDef, worldModel[7]), 11 },
		{ "worldModel9", offsetof(Game::WeaponFullDef, worldModel[8]), 11 },
		{ "worldModel10", offsetof(Game::WeaponFullDef, worldModel[9]), 11 },
		{ "worldModel11", offsetof(Game::WeaponFullDef, worldModel[10]), 11 },
		{ "worldModel12", offsetof(Game::WeaponFullDef, worldModel[11]), 11 },
		{ "worldModel13", offsetof(Game::WeaponFullDef, worldModel[12]), 11 },
		{ "worldModel14", offsetof(Game::WeaponFullDef, worldModel[13]), 11 },
		{ "worldModel15", offsetof(Game::WeaponFullDef, worldModel[14]), 11 },
		{ "worldModel16", offsetof(Game::WeaponFullDef, worldModel[15]), 11 },
		{ "worldClipModel", offsetof(Game::WeaponFullDef, weapDef.worldClipModel), 11 },
		{ "rocketModel", offsetof(Game::WeaponFullDef, weapDef.rocketModel), 11 },
		{ "knifeModel", offsetof(Game::WeaponFullDef, weapDef.knifeModel), 11 },
		{ "worldKnifeModel", offsetof(Game::WeaponFullDef, weapDef.worldKnifeModel), 11 },
		{ "hudIcon", offsetof(Game::WeaponFullDef, weapDef.hudIcon), 12 },
		{ "hudIconRatio", offsetof(Game::WeaponFullDef, weapDef.hudIconRatio), 33 },
		{ "pickupIcon", offsetof(Game::WeaponFullDef, weapDef.pickupIcon), 12 },
		{ "pickupIconRatio", offsetof(Game::WeaponFullDef, weapDef.pickupIconRatio), 34 },
		{ "ammoCounterIcon", offsetof(Game::WeaponFullDef, weapDef.ammoCounterIcon), 12 },
		{ "ammoCounterIconRatio", offsetof(Game::WeaponFullDef, weapDef.ammoCounterIconRatio), 35 },
		{ "ammoCounterClip", offsetof(Game::WeaponFullDef, weapDef.ammoCounterClip), 32 },
		{ "startAmmo", offsetof(Game::WeaponFullDef, weapDef.iStartAmmo), 4 },
		{ "shareAmmo", offsetof(Game::WeaponFullDef, weapDef.sharedAmmo), 6 },
		{ "ammoName", offsetof(Game::WeaponFullDef, weapDef.szAmmoName), 0 },
		{ "clipName", offsetof(Game::WeaponFullDef, weapDef.szClipName), 0 },
		{ "maxAmmo", offsetof(Game::WeaponFullDef, weapDef.iMaxAmmo), 4 },
		{ "clipSize", offsetof(Game::WeaponFullDef, complete.iClipSize), 4 },
		{ "shotCount", offsetof(Game::WeaponFullDef, weapDef.shotCount), 4 },
		{ "sharedAmmoCapName", offsetof(Game::WeaponFullDef, weapDef.szSharedAmmoCapName), 0 },
		{ "sharedAmmoCap", offsetof(Game::WeaponFullDef, weapDef.iSharedAmmoCap), 4 },
		{ "damage", offsetof(Game::WeaponFullDef, weapDef.damage), 4 },
		{ "playerDamage", offsetof(Game::WeaponFullDef, weapDef.playerDamage), 4 },
		{ "meleeDamage", offsetof(Game::WeaponFullDef, weapDef.iMeleeDamage), 4 },
		{ "minDamage", offsetof(Game::WeaponFullDef, weapDef.minDamage), 4 },
		{ "minPlayerDamage", offsetof(Game::WeaponFullDef, weapDef.minPlayerDamage), 4 },
		{ "maxDamageRange", offsetof(Game::WeaponFullDef, weapDef.fMaxDamageRange), 7 },
		{ "minDamageRange", offsetof(Game::WeaponFullDef, weapDef.fMinDamageRange), 7 },
		{ "destabilizationRateTime", offsetof(Game::WeaponFullDef, weapDef.destabilizationRateTime), 7 },
		{ "destabilizationCurvatureMax", offsetof(Game::WeaponFullDef, weapDef.destabilizationCurvatureMax), 7 },
		{ "destabilizeDistance", offsetof(Game::WeaponFullDef, weapDef.destabilizeDistance), 4 },
		{ "fireDelay", offsetof(Game::WeaponFullDef, weapDef.iFireDelay), 9 },
		{ "meleeDelay", offsetof(Game::WeaponFullDef, weapDef.iMeleeDelay), 9 },
		{ "meleeChargeDelay", offsetof(Game::WeaponFullDef, weapDef.meleeChargeDelay), 9 },
		{ "fireTime", offsetof(Game::WeaponFullDef, complete.iFireTime), 9 },
		{ "rechamberTime", offsetof(Game::WeaponFullDef, weapDef.iRechamberTime), 9 },
		{ "rechamberTimeOneHanded", offsetof(Game::WeaponFullDef, weapDef.rechamberTimeOneHanded), 9 },
		{ "rechamberBoltTime", offsetof(Game::WeaponFullDef, weapDef.iRechamberBoltTime), 9 },
		{ "holdFireTime", offsetof(Game::WeaponFullDef, weapDef.iHoldFireTime), 9 },
		{ "detonateTime", offsetof(Game::WeaponFullDef, weapDef.iDetonateTime), 9 },
		{ "detonateDelay", offsetof(Game::WeaponFullDef, weapDef.iDetonateDelay), 9 },
		{ "meleeTime", offsetof(Game::WeaponFullDef, weapDef.iMeleeTime), 9 },
		{ "meleeChargeTime", offsetof(Game::WeaponFullDef, weapDef.meleeChargeTime), 9 },
		{ "reloadTime", offsetof(Game::WeaponFullDef, weapDef.iReloadTime), 9 },
		{ "reloadShowRocketTime", offsetof(Game::WeaponFullDef, weapDef.reloadShowRocketTime), 9 },
		{ "reloadEmptyTime", offsetof(Game::WeaponFullDef, weapDef.iReloadEmptyTime), 9 },
		{ "reloadAddTime", offsetof(Game::WeaponFullDef, weapDef.iReloadAddTime), 9 },
		{ "reloadStartTime", offsetof(Game::WeaponFullDef, weapDef.iReloadStartTime), 9 },
		{ "reloadStartAddTime", offsetof(Game::WeaponFullDef, weapDef.iReloadStartAddTime), 9 },
		{ "reloadEndTime", offsetof(Game::WeaponFullDef, weapDef.iReloadEndTime), 9 },
		{ "dropTime", offsetof(Game::WeaponFullDef, weapDef.iDropTime), 9 },
		{ "raiseTime", offsetof(Game::WeaponFullDef, weapDef.iRaiseTime), 9 },
		{ "altDropTime", offsetof(Game::WeaponFullDef, weapDef.iAltDropTime), 9 },
		{ "altRaiseTime", offsetof(Game::WeaponFullDef, complete.iAltRaiseTime), 9 },
		{ "quickDropTime", offsetof(Game::WeaponFullDef, weapDef.quickDropTime), 9 },
		{ "quickRaiseTime", offsetof(Game::WeaponFullDef, weapDef.quickRaiseTime), 9 },
		{ "firstRaiseTime", offsetof(Game::WeaponFullDef, complete.iFirstRaiseTime), 9 },
		{ "breachRaiseTime", offsetof(Game::WeaponFullDef, weapDef.iBreachRaiseTime), 9 },
		{ "emptyRaiseTime", offsetof(Game::WeaponFullDef, weapDef.iEmptyRaiseTime), 9 },
		{ "emptyDropTime", offsetof(Game::WeaponFullDef, weapDef.iEmptyDropTime), 9 },
		{ "sprintInTime", offsetof(Game::WeaponFullDef, weapDef.sprintInTime), 9 },
		{ "sprintLoopTime", offsetof(Game::WeaponFullDef, weapDef.sprintLoopTime), 9 },
		{ "sprintOutTime", offsetof(Game::WeaponFullDef, weapDef.sprintOutTime), 9 },
		{ "stunnedTimeBegin", offsetof(Game::WeaponFullDef, weapDef.stunnedTimeBegin), 9 },
		{ "stunnedTimeLoop", offsetof(Game::WeaponFullDef, weapDef.stunnedTimeLoop), 9 },
		{ "stunnedTimeEnd", offsetof(Game::WeaponFullDef, weapDef.stunnedTimeEnd), 9 },
		{ "nightVisionWearTime", offsetof(Game::WeaponFullDef, weapDef.nightVisionWearTime), 9 },
		{ "nightVisionWearTimeFadeOutEnd", offsetof(Game::WeaponFullDef, weapDef.nightVisionWearTimeFadeOutEnd), 9 },
		{ "nightVisionWearTimePowerUp", offsetof(Game::WeaponFullDef, weapDef.nightVisionWearTimePowerUp), 9 },
		{ "nightVisionRemoveTime", offsetof(Game::WeaponFullDef, weapDef.nightVisionRemoveTime), 9 },
		{ "nightVisionRemoveTimePowerDown", offsetof(Game::WeaponFullDef, weapDef.nightVisionRemoveTimePowerDown), 9 },
		{ "nightVisionRemoveTimeFadeInStart", offsetof(Game::WeaponFullDef, weapDef.nightVisionRemoveTimeFadeInStart), 9 },
		{ "fuseTime", offsetof(Game::WeaponFullDef, weapDef.fuseTime), 9 },
		{ "aifuseTime", offsetof(Game::WeaponFullDef, weapDef.aiFuseTime), 9 },
		{ "lockonSupported", offsetof(Game::WeaponFullDef, weapDef.lockonSupported), 6 },
		{ "requireLockonToFire", offsetof(Game::WeaponFullDef, weapDef.requireLockonToFire), 6 },
		{ "bigExplosion", offsetof(Game::WeaponFullDef, weapDef.bigExplosion), 6 },
		{ "noAdsWhenMagEmpty", offsetof(Game::WeaponFullDef, weapDef.noAdsWhenMagEmpty), 6 },
		{ "inheritsPerks", offsetof(Game::WeaponFullDef, weapDef.inheritsPerks), 6 },
		{ "avoidDropCleanup", offsetof(Game::WeaponFullDef, weapDef.avoidDropCleanup), 6 },
		{ "autoAimRange", offsetof(Game::WeaponFullDef, weapDef.autoAimRange), 7 },
		{ "aimAssistRange", offsetof(Game::WeaponFullDef, weapDef.aimAssistRange), 7 },
		{ "aimAssistRangeAds", offsetof(Game::WeaponFullDef, weapDef.aimAssistRangeAds), 7 },
		{ "aimPadding", offsetof(Game::WeaponFullDef, weapDef.aimPadding), 7 },
		{ "enemyCrosshairRange", offsetof(Game::WeaponFullDef, weapDef.enemyCrosshairRange), 7 },
		{ "crosshairColorChange", offsetof(Game::WeaponFullDef, weapDef.crosshairColorChange), 6 },
		{ "moveSpeedScale", offsetof(Game::WeaponFullDef, weapDef.moveSpeedScale), 7 },
		{ "adsMoveSpeedScale", offsetof(Game::WeaponFullDef, weapDef.adsMoveSpeedScale), 7 },
		{ "sprintDurationScale", offsetof(Game::WeaponFullDef, weapDef.sprintDurationScale), 7 },
		{ "idleCrouchFactor", offsetof(Game::WeaponFullDef, weapDef.fIdleCrouchFactor), 7 },
		{ "idleProneFactor", offsetof(Game::WeaponFullDef, weapDef.fIdleProneFactor), 7 },
		{ "gunMaxPitch", offsetof(Game::WeaponFullDef, weapDef.fGunMaxPitch), 7 },
		{ "gunMaxYaw", offsetof(Game::WeaponFullDef, weapDef.fGunMaxYaw), 7 },
		{ "swayMaxAngle", offsetof(Game::WeaponFullDef, weapDef.swayMaxAngle), 7 },
		{ "swayLerpSpeed", offsetof(Game::WeaponFullDef, weapDef.swayLerpSpeed), 7 },
		{ "swayPitchScale", offsetof(Game::WeaponFullDef, weapDef.swayPitchScale), 7 },
		{ "swayYawScale", offsetof(Game::WeaponFullDef, weapDef.swayYawScale), 7 },
		{ "swayHorizScale", offsetof(Game::WeaponFullDef, weapDef.swayHorizScale), 7 },
		{ "swayVertScale", offsetof(Game::WeaponFullDef, weapDef.swayVertScale), 7 },
		{ "swayShellShockScale", offsetof(Game::WeaponFullDef, weapDef.swayShellShockScale), 7 },
		{ "adsSwayMaxAngle", offsetof(Game::WeaponFullDef, weapDef.adsSwayMaxAngle), 7 },
		{ "adsSwayLerpSpeed", offsetof(Game::WeaponFullDef, weapDef.adsSwayLerpSpeed), 7 },
		{ "adsSwayPitchScale", offsetof(Game::WeaponFullDef, weapDef.adsSwayPitchScale), 7 },
		{ "adsSwayYawScale", offsetof(Game::WeaponFullDef, weapDef.adsSwayYawScale), 7 },
		{ "adsSwayHorizScale", offsetof(Game::WeaponFullDef, weapDef.adsSwayHorizScale), 7 },
		{ "adsSwayVertScale", offsetof(Game::WeaponFullDef, weapDef.adsSwayVertScale), 7 },
		{ "rifleBullet", offsetof(Game::WeaponFullDef, weapDef.bRifleBullet), 6 },
		{ "armorPiercing", offsetof(Game::WeaponFullDef, weapDef.armorPiercing), 6 },
		{ "boltAction", offsetof(Game::WeaponFullDef, weapDef.bBoltAction), 6 },
		{ "aimDownSight", offsetof(Game::WeaponFullDef, weapDef.aimDownSight), 6 },
		{ "rechamberWhileAds", offsetof(Game::WeaponFullDef, weapDef.bRechamberWhileAds), 6 },
		{ "bBulletExplosiveDamage", offsetof(Game::WeaponFullDef, weapDef.bBulletExplosiveDamage), 6 },
		{ "adsViewErrorMin", offsetof(Game::WeaponFullDef, weapDef.adsViewErrorMin), 7 },
		{ "adsViewErrorMax", offsetof(Game::WeaponFullDef, weapDef.adsViewErrorMax), 7 },
		{ "clipOnly", offsetof(Game::WeaponFullDef, weapDef.bClipOnly), 6 },
		{ "noAmmoPickup", offsetof(Game::WeaponFullDef, weapDef.noAmmoPickup), 6 },
		{ "cookOffHold", offsetof(Game::WeaponFullDef, weapDef.bCookOffHold), 6 },
		{ "adsFire", offsetof(Game::WeaponFullDef, weapDef.adsFireOnly), 6 },
		{ "cancelAutoHolsterWhenEmpty", offsetof(Game::WeaponFullDef, weapDef.cancelAutoHolsterWhenEmpty), 6 },
		{ "disableSwitchToWhenEmpty", offsetof(Game::WeaponFullDef, weapDef.disableSwitchToWhenEmpty), 6 },
		{ "suppressAmmoReserveDisplay", offsetof(Game::WeaponFullDef, weapDef.suppressAmmoReserveDisplay), 6 },
		{ "enhanced", offsetof(Game::WeaponFullDef, complete.enhanced), 6 },
		{ "motionTracker", offsetof(Game::WeaponFullDef, complete.motionTracker), 6 },
		{ "laserSightDuringNightvision", offsetof(Game::WeaponFullDef, weapDef.laserSightDuringNightvision), 6 },
		{ "markableViewmodel", offsetof(Game::WeaponFullDef, weapDef.markableViewmodel), 6 },
		{ "physCollmap", offsetof(Game::WeaponFullDef, weapDef.physCollmap), 13 },
		{ "noDualWield", offsetof(Game::WeaponFullDef, weapDef.noDualWield), 6 },
		{ "dualWieldViewModelOffset", offsetof(Game::WeaponFullDef, weapDef.dualWieldViewModelOffset), 7 },
		{ "killIcon", offsetof(Game::WeaponFullDef, complete.killIcon), 12 },
		{ "killIconRatio", offsetof(Game::WeaponFullDef, weapDef.killIconRatio), 36 },
		{ "flipKillIcon", offsetof(Game::WeaponFullDef, weapDef.flipKillIcon), 6 },
		{ "dpadIcon", offsetof(Game::WeaponFullDef, complete.dpadIcon), 12 },
		{ "dpadIconRatio", offsetof(Game::WeaponFullDef, complete.dpadIconRatio), 37 },
		{ "dpadIconShowsAmmo", offsetof(Game::WeaponFullDef, complete.dpadIconShowsAmmo), 6 },
		{ "noPartialReload", offsetof(Game::WeaponFullDef, weapDef.bNoPartialReload), 6 },
		{ "segmentedReload", offsetof(Game::WeaponFullDef, weapDef.bSegmentedReload), 6 },
		{ "reloadAmmoAdd", offsetof(Game::WeaponFullDef, weapDef.iReloadAmmoAdd), 4 },
		{ "reloadStartAdd", offsetof(Game::WeaponFullDef, weapDef.iReloadStartAdd), 4 },
		{ "altWeapon", offsetof(Game::WeaponFullDef, complete.szAltWeaponName), 0 },
		{ "dropAmmoMin", offsetof(Game::WeaponFullDef, weapDef.ammoDropStockMin), 4 },
		{ "dropAmmoMax", offsetof(Game::WeaponFullDef, complete.ammoDropStockMax), 4 },
		{ "ammoDropClipPercentMin", offsetof(Game::WeaponFullDef, weapDef.ammoDropClipPercentMin), 4 },
		{ "ammoDropClipPercentMax", offsetof(Game::WeaponFullDef, weapDef.ammoDropClipPercentMax), 4 },
		{ "blocksProne", offsetof(Game::WeaponFullDef, weapDef.blocksProne), 6 },
		{ "silenced", offsetof(Game::WeaponFullDef, weapDef.silenced), 6 },
		{ "isRollingGrenade", offsetof(Game::WeaponFullDef, weapDef.isRollingGrenade), 6 },
		{ "explosionRadius", offsetof(Game::WeaponFullDef, weapDef.iExplosionRadius), 4 },
		{ "explosionRadiusMin", offsetof(Game::WeaponFullDef, weapDef.iExplosionRadiusMin), 4 },
		{ "explosionInnerDamage", offsetof(Game::WeaponFullDef, weapDef.iExplosionInnerDamage), 4 },
		{ "explosionOuterDamage", offsetof(Game::WeaponFullDef, weapDef.iExplosionOuterDamage), 4 },
		{ "damageConeAngle", offsetof(Game::WeaponFullDef, weapDef.damageConeAngle), 7 },
		{ "bulletExplDmgMult", offsetof(Game::WeaponFullDef, weapDef.bulletExplDmgMult), 7 },
		{ "bulletExplRadiusMult", offsetof(Game::WeaponFullDef, weapDef.bulletExplRadiusMult), 7 },
		{ "projectileSpeed", offsetof(Game::WeaponFullDef, weapDef.iProjectileSpeed), 4 },
		{ "projectileSpeedUp", offsetof(Game::WeaponFullDef, weapDef.iProjectileSpeedUp), 4 },
		{ "projectileSpeedForward", offsetof(Game::WeaponFullDef, weapDef.iProjectileSpeedForward), 4 },
		{ "projectileActivateDist", offsetof(Game::WeaponFullDef, weapDef.iProjectileActivateDist), 4 },
		{ "projectileLifetime", offsetof(Game::WeaponFullDef, weapDef.projLifetime), 7 },
		{ "timeToAccelerate", offsetof(Game::WeaponFullDef, weapDef.timeToAccelerate), 7 },
		{ "projectileCurvature", offsetof(Game::WeaponFullDef, weapDef.projectileCurvature), 7 },
		{ "projectileModel", offsetof(Game::WeaponFullDef, weapDef.projectileModel), 11 },
		{ "projExplosionType", offsetof(Game::WeaponFullDef, weapDef.projExplosion), 22 },
		{ "projExplosionEffect", offsetof(Game::WeaponFullDef, weapDef.projExplosionEffect), 10 },
		{ "projExplosionEffectForceNormalUp", offsetof(Game::WeaponFullDef, weapDef.projExplosionEffectForceNormalUp), 6 },
		{ "projExplosionSound", offsetof(Game::WeaponFullDef, weapDef.projExplosionSound), 14 },
		{ "projDudEffect", offsetof(Game::WeaponFullDef, weapDef.projDudEffect), 10 },
		{ "projDudSound", offsetof(Game::WeaponFullDef, weapDef.projDudSound), 14 },
		{ "projImpactExplode", offsetof(Game::WeaponFullDef, weapDef.bProjImpactExplode), 6 },
		{ "stickiness", offsetof(Game::WeaponFullDef, weapDef.stickiness), 28 },
		{ "stickToPlayers", offsetof(Game::WeaponFullDef, weapDef.stickToPlayers), 6 },
		{ "hasDetonator", offsetof(Game::WeaponFullDef, weapDef.hasDetonator), 6 },
		{ "disableFiring", offsetof(Game::WeaponFullDef, weapDef.disableFiring), 6 },
		{ "timedDetonation", offsetof(Game::WeaponFullDef, weapDef.timedDetonation), 6 },
		{ "rotate", offsetof(Game::WeaponFullDef, weapDef.rotate), 6 },
		{ "holdButtonToThrow", offsetof(Game::WeaponFullDef, weapDef.holdButtonToThrow), 6 },
		{ "freezeMovementWhenFiring", offsetof(Game::WeaponFullDef, weapDef.freezeMovementWhenFiring), 6 },
		{ "lowAmmoWarningThreshold", offsetof(Game::WeaponFullDef, weapDef.lowAmmoWarningThreshold), 7 },
		{ "ricochetChance", offsetof(Game::WeaponFullDef, weapDef.ricochetChance), 7 },
		{ "offhandHoldIsCancelable", offsetof(Game::WeaponFullDef, weapDef.offhandHoldIsCancelable), 6 },
		{ "parallelDefaultBounce", offsetof(Game::WeaponFullDef, parallelBounce[0]), 7 },
		{ "parallelBarkBounce", offsetof(Game::WeaponFullDef, parallelBounce[1]), 7 },
		{ "parallelBrickBounce", offsetof(Game::WeaponFullDef, parallelBounce[2]), 7 },
		{ "parallelCarpetBounce", offsetof(Game::WeaponFullDef, parallelBounce[3]), 7 },
		{ "parallelClothBounce", offsetof(Game::WeaponFullDef, parallelBounce[4]), 7 },
		{ "parallelConcreteBounce", offsetof(Game::WeaponFullDef, parallelBounce[5]), 7 },
		{ "parallelDirtBounce", offsetof(Game::WeaponFullDef, parallelBounce[6]), 7 },
		{ "parallelFleshBounce", offsetof(Game::WeaponFullDef, parallelBounce[7]), 7 },
		{ "parallelFoliageBounce", offsetof(Game::WeaponFullDef, parallelBounce[8]), 7 },
		{ "parallelGlassBounce", offsetof(Game::WeaponFullDef, parallelBounce[9]), 7 },
		{ "parallelGrassBounce", offsetof(Game::WeaponFullDef, parallelBounce[10]), 7 },
		{ "parallelGravelBounce", offsetof(Game::WeaponFullDef, parallelBounce[11]), 7 },
		{ "parallelIceBounce", offsetof(Game::WeaponFullDef, parallelBounce[12]), 7 },
		{ "parallelMetalBounce", offsetof(Game::WeaponFullDef, parallelBounce[13]), 7 },
		{ "parallelMudBounce", offsetof(Game::WeaponFullDef, parallelBounce[14]), 7 },
		{ "parallelPaperBounce", offsetof(Game::WeaponFullDef, parallelBounce[15]), 7 },
		{ "parallelPlasterBounce", offsetof(Game::WeaponFullDef, parallelBounce[16]), 7 },
		{ "parallelRockBounce", offsetof(Game::WeaponFullDef, parallelBounce[17]), 7 },
		{ "parallelSandBounce", offsetof(Game::WeaponFullDef, parallelBounce[18]), 7 },
		{ "parallelSnowBounce", offsetof(Game::WeaponFullDef, parallelBounce[19]), 7 },
		{ "parallelWaterBounce", offsetof(Game::WeaponFullDef, parallelBounce[20]), 7 },
		{ "parallelWoodBounce", offsetof(Game::WeaponFullDef, parallelBounce[21]), 7 },
		{ "parallelAsphaltBounce", offsetof(Game::WeaponFullDef, parallelBounce[22]), 7 },
		{ "parallelCeramicBounce", offsetof(Game::WeaponFullDef, parallelBounce[23]), 7 },
		{ "parallelPlasticBounce", offsetof(Game::WeaponFullDef, parallelBounce[24]), 7 },
		{ "parallelRubberBounce", offsetof(Game::WeaponFullDef, parallelBounce[25]), 7 },
		{ "parallelCushionBounce", offsetof(Game::WeaponFullDef, parallelBounce[26]), 7 },
		{ "parallelFruitBounce", offsetof(Game::WeaponFullDef, parallelBounce[27]), 7 },
		{ "parallelPaintedMetalBounce", offsetof(Game::WeaponFullDef, parallelBounce[28]), 7 },
		{ "parallelRiotShieldBounce", offsetof(Game::WeaponFullDef, parallelBounce[29]), 7 },
		{ "parallelSlushBounce", offsetof(Game::WeaponFullDef, parallelBounce[30]), 7 },
		{ "perpendicularDefaultBounce", offsetof(Game::WeaponFullDef, perpendicularBounce[0]), 7 },
		{ "perpendicularBarkBounce", offsetof(Game::WeaponFullDef, perpendicularBounce[1]), 7 },
		{ "perpendicularBrickBounce", offsetof(Game::WeaponFullDef, perpendicularBounce[2]), 7 },
		{ "perpendicularCarpetBounce", offsetof(Game::WeaponFullDef, perpendicularBounce[3]), 7 },
		{ "perpendicularClothBounce", offsetof(Game::WeaponFullDef, perpendicularBounce[4]), 7 },
		{ "perpendicularConcreteBounce", offsetof(Game::WeaponFullDef, perpendicularBounce[5]), 7 },
		{ "perpendicularDirtBounce", offsetof(Game::WeaponFullDef, perpendicularBounce[6]), 7 },
		{ "perpendicularFleshBounce", offsetof(Game::WeaponFullDef, perpendicularBounce[7]), 7 },
		{ "perpendicularFoliageBounce", offsetof(Game::WeaponFullDef, perpendicularBounce[8]), 7 },
		{ "perpendicularGlassBounce", offsetof(Game::WeaponFullDef, perpendicularBounce[9]), 7 },
		{ "perpendicularGrassBounce", offsetof(Game::WeaponFullDef, perpendicularBounce[10]), 7 },
		{ "perpendicularGravelBounce", offsetof(Game::WeaponFullDef, perpendicularBounce[11]), 7 },
		{ "perpendicularIceBounce", offsetof(Game::WeaponFullDef, perpendicularBounce[12]), 7 },
		{ "perpendicularMetalBounce", offsetof(Game::WeaponFullDef, perpendicularBounce[13]), 7 },
		{ "perpendicularMudBounce", offsetof(Game::WeaponFullDef, perpendicularBounce[14]), 7 },
		{ "perpendicularPaperBounce", offsetof(Game::WeaponFullDef, perpendicularBounce[15]), 7 },
		{ "perpendicularPlasterBounce", offsetof(Game::WeaponFullDef, perpendicularBounce[16]), 7 },
		{ "perpendicularRockBounce", offsetof(Game::WeaponFullDef, perpendicularBounce[17]), 7 },
		{ "perpendicularSandBounce", offsetof(Game::WeaponFullDef, perpendicularBounce[18]), 7 },
		{ "perpendicularSnowBounce", offsetof(Game::WeaponFullDef, perpendicularBounce[19]), 7 },
		{ "perpendicularWaterBounce", offsetof(Game::WeaponFullDef, perpendicularBounce[20]), 7 },
		{ "perpendicularWoodBounce", offsetof(Game::WeaponFullDef, perpendicularBounce[21]), 7 },
		{ "perpendicularAsphaltBounce", offsetof(Game::WeaponFullDef, perpendicularBounce[22]), 7 },
		{ "perpendicularCeramicBounce", offsetof(Game::WeaponFullDef, parallelBounce[23]), 7 },
		{ "perpendicularPlasticBounce", offsetof(Game::WeaponFullDef, parallelBounce[24]), 7 },
		{ "perpendicularRubberBounce", offsetof(Game::WeaponFullDef, parallelBounce[25]), 7 },
		{ "perpendicularCushionBounce", offsetof(Game::WeaponFullDef, perpendicularBounce[26]), 7 },
		{ "perpendicularFruitBounce", offsetof(Game::WeaponFullDef, perpendicularBounce[27]), 7 },
		{ "perpendicularPaintedMetalBounce", offsetof(Game::WeaponFullDef, perpendicularBounce[28]), 7 },
		{ "perpendicularRiotShieldBounce", offsetof(Game::WeaponFullDef, perpendicularBounce[29]), 7 },
		{ "perpendicularSlushBounce", offsetof(Game::WeaponFullDef, perpendicularBounce[30]), 7 },
		{ "projTrailEffect", offsetof(Game::WeaponFullDef, weapDef.projTrailEffect), 10 },
		{ "projBeaconEffect", offsetof(Game::WeaponFullDef, weapDef.projBeaconEffect), 10 },
		{ "projectileRed", offsetof(Game::WeaponFullDef, weapDef.vProjectileColor[0]), 7 },
		{ "projectileGreen", offsetof(Game::WeaponFullDef, weapDef.vProjectileColor[1]), 7 },
		{ "projectileBlue", offsetof(Game::WeaponFullDef, weapDef.vProjectileColor[2]), 7 },
		{ "guidedMissileType", offsetof(Game::WeaponFullDef, weapDef.guidedMissileType), 26 },
		{ "maxSteeringAccel", offsetof(Game::WeaponFullDef, weapDef.maxSteeringAccel), 7 },
		{ "projIgnitionDelay", offsetof(Game::WeaponFullDef, weapDef.projIgnitionDelay), 4 },
		{ "projIgnitionEffect", offsetof(Game::WeaponFullDef, weapDef.projIgnitionEffect), 10 },
		{ "projIgnitionSound", offsetof(Game::WeaponFullDef, weapDef.projIgnitionSound), 14 },
		{ "adsTransInTime", offsetof(Game::WeaponFullDef, complete.iAdsTransInTime), 9 },
		{ "adsTransOutTime", offsetof(Game::WeaponFullDef, complete.iAdsTransOutTime), 9 },
		{ "adsIdleAmount", offsetof(Game::WeaponFullDef, weapDef.fAdsIdleAmount), 7 },
		{ "adsIdleSpeed", offsetof(Game::WeaponFullDef, weapDef.adsIdleSpeed), 7 },
		{ "adsZoomFov", offsetof(Game::WeaponFullDef, complete.fAdsZoomFov), 7 },
		{ "adsZoomInFrac", offsetof(Game::WeaponFullDef, weapDef.fAdsZoomInFrac), 7 },
		{ "adsZoomOutFrac", offsetof(Game::WeaponFullDef, weapDef.fAdsZoomOutFrac), 7 },
		{ "adsOverlayShader", offsetof(Game::WeaponFullDef, weapDef.overlayMaterial), 12 },
		{ "adsOverlayShaderLowRes", offsetof(Game::WeaponFullDef, weapDef.overlayMaterialLowRes), 12 },
		{ "adsOverlayShaderEMP", offsetof(Game::WeaponFullDef, weapDef.overlayMaterialEMP), 12 },
		{ "adsOverlayShaderEMPLowRes", offsetof(Game::WeaponFullDef, weapDef.overlayMaterialEMPLowRes), 12 },
		{ "adsOverlayReticle", offsetof(Game::WeaponFullDef, weapDef.overlayReticle), 18 },
		{ "adsOverlayInterface", offsetof(Game::WeaponFullDef, weapDef.overlayInterface), 29 },
		{ "adsOverlayWidth", offsetof(Game::WeaponFullDef, weapDef.overlayWidth), 7 },
		{ "adsOverlayHeight", offsetof(Game::WeaponFullDef, weapDef.overlayHeight), 7 },
		{ "adsOverlayWidthSplitscreen", offsetof(Game::WeaponFullDef, weapDef.overlayWidthSplitscreen), 7 },
		{ "adsOverlayHeightSplitscreen", offsetof(Game::WeaponFullDef, weapDef.overlayHeightSplitscreen), 7 },
		{ "adsBobFactor", offsetof(Game::WeaponFullDef, weapDef.fAdsBobFactor), 7 },
		{ "adsViewBobMult", offsetof(Game::WeaponFullDef, weapDef.fAdsViewBobMult), 7 },
		{ "adsAimPitch", offsetof(Game::WeaponFullDef, weapDef.fAdsAimPitch), 7 },
		{ "adsCrosshairInFrac", offsetof(Game::WeaponFullDef, weapDef.fAdsCrosshairInFrac), 7 },
		{ "adsCrosshairOutFrac", offsetof(Game::WeaponFullDef, weapDef.fAdsCrosshairOutFrac), 7 },
		{ "adsReloadTransTime", offsetof(Game::WeaponFullDef, weapDef.iPositionReloadTransTime), 9 },
		{ "adsGunKickReducedKickBullets", offsetof(Game::WeaponFullDef, weapDef.adsGunKickReducedKickBullets), 4 },
		{ "adsGunKickReducedKickPercent", offsetof(Game::WeaponFullDef, weapDef.adsGunKickReducedKickPercent), 7 },
		{ "adsGunKickPitchMin", offsetof(Game::WeaponFullDef, weapDef.fAdsGunKickPitchMin), 7 },
		{ "adsGunKickPitchMax", offsetof(Game::WeaponFullDef, weapDef.fAdsGunKickPitchMax), 7 },
		{ "adsGunKickYawMin", offsetof(Game::WeaponFullDef, weapDef.fAdsGunKickYawMin), 7 },
		{ "adsGunKickYawMax", offsetof(Game::WeaponFullDef, weapDef.fAdsGunKickYawMax), 7 },
		{ "adsGunKickAccel", offsetof(Game::WeaponFullDef, weapDef.fAdsGunKickAccel), 7 },
		{ "adsGunKickSpeedMax", offsetof(Game::WeaponFullDef, weapDef.fAdsGunKickSpeedMax), 7 },
		{ "adsGunKickSpeedDecay", offsetof(Game::WeaponFullDef, weapDef.fAdsGunKickSpeedDecay), 7 },
		{ "adsGunKickStaticDecay", offsetof(Game::WeaponFullDef, weapDef.fAdsGunKickStaticDecay), 7 },
		{ "adsViewKickPitchMin", offsetof(Game::WeaponFullDef, weapDef.fAdsViewKickPitchMin), 7 },
		{ "adsViewKickPitchMax", offsetof(Game::WeaponFullDef, weapDef.fAdsViewKickPitchMax), 7 },
		{ "adsViewKickYawMin", offsetof(Game::WeaponFullDef, weapDef.fAdsViewKickYawMin), 7 },
		{ "adsViewKickYawMax", offsetof(Game::WeaponFullDef, weapDef.fAdsViewKickYawMax), 7 },
		{ "adsViewKickCenterSpeed", offsetof(Game::WeaponFullDef, complete.fAdsViewKickCenterSpeed), 7 },
		{ "adsSpread", offsetof(Game::WeaponFullDef, weapDef.fAdsSpread), 7 },
		{ "guidedMissileType", offsetof(Game::WeaponFullDef, weapDef.guidedMissileType), 26 },
		{ "hipSpreadStandMin", offsetof(Game::WeaponFullDef, weapDef.fHipSpreadStandMin), 7 },
		{ "hipSpreadDuckedMin", offsetof(Game::WeaponFullDef, weapDef.fHipSpreadDuckedMin), 7 },
		{ "hipSpreadProneMin", offsetof(Game::WeaponFullDef, weapDef.fHipSpreadProneMin), 7 },
		{ "hipSpreadMax", offsetof(Game::WeaponFullDef, weapDef.hipSpreadStandMax), 7 },
		{ "hipSpreadDuckedMax", offsetof(Game::WeaponFullDef, weapDef.hipSpreadDuckedMax), 7 },
		{ "hipSpreadProneMax", offsetof(Game::WeaponFullDef, weapDef.hipSpreadProneMax), 7 },
		{ "hipSpreadDecayRate", offsetof(Game::WeaponFullDef, weapDef.fHipSpreadDecayRate), 7 },
		{ "hipSpreadFireAdd", offsetof(Game::WeaponFullDef, weapDef.fHipSpreadFireAdd), 7 },
		{ "hipSpreadTurnAdd", offsetof(Game::WeaponFullDef, weapDef.fHipSpreadTurnAdd), 7 },
		{ "hipSpreadMoveAdd", offsetof(Game::WeaponFullDef, weapDef.fHipSpreadMoveAdd), 7 },
		{ "hipSpreadDuckedDecay", offsetof(Game::WeaponFullDef, weapDef.fHipSpreadDuckedDecay), 7 },
		{ "hipSpreadProneDecay", offsetof(Game::WeaponFullDef, weapDef.fHipSpreadProneDecay), 7 },
		{ "hipReticleSidePos", offsetof(Game::WeaponFullDef, weapDef.fHipReticleSidePos), 7 },
		{ "hipIdleAmount", offsetof(Game::WeaponFullDef, weapDef.fHipIdleAmount), 7 },
		{ "hipIdleSpeed", offsetof(Game::WeaponFullDef, weapDef.hipIdleSpeed), 7 },
		{ "hipGunKickReducedKickBullets", offsetof(Game::WeaponFullDef, weapDef.hipGunKickReducedKickBullets), 4 },
		{ "hipGunKickReducedKickPercent", offsetof(Game::WeaponFullDef, weapDef.hipGunKickReducedKickPercent), 7 },
		{ "hipGunKickPitchMin", offsetof(Game::WeaponFullDef, weapDef.fHipGunKickPitchMin), 7 },
		{ "hipGunKickPitchMax", offsetof(Game::WeaponFullDef, weapDef.fHipGunKickPitchMax), 7 },
		{ "hipGunKickYawMin", offsetof(Game::WeaponFullDef, weapDef.fHipGunKickYawMin), 7 },
		{ "hipGunKickYawMax", offsetof(Game::WeaponFullDef, weapDef.fHipGunKickYawMax), 7 },
		{ "hipGunKickAccel", offsetof(Game::WeaponFullDef, weapDef.fHipGunKickAccel), 7 },
		{ "hipGunKickSpeedMax", offsetof(Game::WeaponFullDef, weapDef.fHipGunKickSpeedMax), 7 },
		{ "hipGunKickSpeedDecay", offsetof(Game::WeaponFullDef, weapDef.fHipGunKickSpeedDecay), 7 },
		{ "hipGunKickStaticDecay", offsetof(Game::WeaponFullDef, weapDef.fHipGunKickStaticDecay), 7 },
		{ "hipViewKickPitchMin", offsetof(Game::WeaponFullDef, weapDef.fHipViewKickPitchMin), 7 },
		{ "hipViewKickPitchMax", offsetof(Game::WeaponFullDef, weapDef.fHipViewKickPitchMax), 7 },
		{ "hipViewKickYawMin", offsetof(Game::WeaponFullDef, weapDef.fHipViewKickYawMin), 7 },
		{ "hipViewKickYawMax", offsetof(Game::WeaponFullDef, weapDef.fHipViewKickYawMax), 7 },
		{ "hipViewKickCenterSpeed", offsetof(Game::WeaponFullDef, complete.fHipViewKickCenterSpeed), 7 },
		{ "leftArc", offsetof(Game::WeaponFullDef, weapDef.leftArc), 7 },
		{ "rightArc", offsetof(Game::WeaponFullDef, weapDef.rightArc), 7 },
		{ "topArc", offsetof(Game::WeaponFullDef, weapDef.topArc), 7 },
		{ "bottomArc", offsetof(Game::WeaponFullDef, weapDef.bottomArc), 7 },
		{ "accuracy", offsetof(Game::WeaponFullDef, weapDef.accuracy), 7 },
		{ "aiSpread", offsetof(Game::WeaponFullDef, weapDef.aiSpread), 7 },
		{ "playerSpread", offsetof(Game::WeaponFullDef, weapDef.playerSpread), 7 },
		{ "maxVertTurnSpeed", offsetof(Game::WeaponFullDef, weapDef.maxTurnSpeed[0]), 7 },
		{ "maxHorTurnSpeed", offsetof(Game::WeaponFullDef, weapDef.maxTurnSpeed[1]), 7 },
		{ "minVertTurnSpeed", offsetof(Game::WeaponFullDef, weapDef.minTurnSpeed[0]), 7 },
		{ "minHorTurnSpeed", offsetof(Game::WeaponFullDef, weapDef.minTurnSpeed[1]), 7 },
		{ "pitchConvergenceTime", offsetof(Game::WeaponFullDef, weapDef.pitchConvergenceTime), 7 },
		{ "yawConvergenceTime", offsetof(Game::WeaponFullDef, weapDef.yawConvergenceTime), 7 },
		{ "suppressionTime", offsetof(Game::WeaponFullDef, weapDef.suppressTime), 7 },
		{ "maxRange", offsetof(Game::WeaponFullDef, weapDef.maxRange), 7 },
		{ "animHorRotateInc", offsetof(Game::WeaponFullDef, weapDef.fAnimHorRotateInc), 7 },
		{ "playerPositionDist", offsetof(Game::WeaponFullDef, weapDef.fPlayerPositionDist), 7 },
		{ "stance", offsetof(Game::WeaponFullDef, weapDef.stance), 21 },
		{ "useHintString", offsetof(Game::WeaponFullDef, weapDef.szUseHintString), 0 },
		{ "dropHintString", offsetof(Game::WeaponFullDef, weapDef.dropHintString), 0 },
		{ "horizViewJitter", offsetof(Game::WeaponFullDef, weapDef.horizViewJitter), 7 },
		{ "vertViewJitter", offsetof(Game::WeaponFullDef, weapDef.vertViewJitter), 7 },
		{ "scanSpeed", offsetof(Game::WeaponFullDef, weapDef.scanSpeed), 7 },
		{ "scanAccel", offsetof(Game::WeaponFullDef, weapDef.scanAccel), 7 },
		{ "scanPauseTime", offsetof(Game::WeaponFullDef, weapDef.scanPauseTime), 9 },
		{ "fightDist", offsetof(Game::WeaponFullDef, weapDef.fightDist), 7 },
		{ "maxDist", offsetof(Game::WeaponFullDef, weapDef.maxDist), 7 },
		{ "aiVsAiAccuracyGraph", offsetof(Game::WeaponFullDef, weapDef.accuracyGraphName[0]), 0 },
		{ "aiVsPlayerAccuracyGraph", offsetof(Game::WeaponFullDef, weapDef.accuracyGraphName[1]), 0 },
		{ "locNone", offsetof(Game::WeaponFullDef, locationDamageMultipliers[0]), 7 },
		{ "locHelmet", offsetof(Game::WeaponFullDef, locationDamageMultipliers[1]), 7 },
		{ "locHead", offsetof(Game::WeaponFullDef, locationDamageMultipliers[2]), 7 },
		{ "locNeck", offsetof(Game::WeaponFullDef, locationDamageMultipliers[3]), 7 },
		{ "locTorsoUpper", offsetof(Game::WeaponFullDef, locationDamageMultipliers[4]), 7 },
		{ "locTorsoLower", offsetof(Game::WeaponFullDef, locationDamageMultipliers[5]), 7 },
		{ "locRightArmUpper", offsetof(Game::WeaponFullDef, locationDamageMultipliers[6]), 7 },
		{ "locRightArmLower", offsetof(Game::WeaponFullDef, locationDamageMultipliers[8]), 7 },
		{ "locRightHand", offsetof(Game::WeaponFullDef, locationDamageMultipliers[10]), 7 },
		{ "locLeftArmUpper", offsetof(Game::WeaponFullDef, locationDamageMultipliers[7]), 7 },
		{ "locLeftArmLower", offsetof(Game::WeaponFullDef, locationDamageMultipliers[9]), 7 },
		{ "locLeftHand", offsetof(Game::WeaponFullDef, locationDamageMultipliers[11]), 7 },
		{ "locRightLegUpper", offsetof(Game::WeaponFullDef, locationDamageMultipliers[12]), 7 },
		{ "locRightLegLower", offsetof(Game::WeaponFullDef, locationDamageMultipliers[14]), 7 },
		{ "locRightFoot", offsetof(Game::WeaponFullDef, locationDamageMultipliers[16]), 7 },
		{ "locLeftLegUpper", offsetof(Game::WeaponFullDef, locationDamageMultipliers[13]), 7 },
		{ "locLeftLegLower", offsetof(Game::WeaponFullDef, locationDamageMultipliers[15]), 7 },
		{ "locLeftFoot", offsetof(Game::WeaponFullDef, locationDamageMultipliers[17]), 7 },
		{ "locGun", offsetof(Game::WeaponFullDef, locationDamageMultipliers[18]), 7 },
		{ "fireRumble", offsetof(Game::WeaponFullDef, weapDef.fireRumble), 0 },
		{ "meleeImpactRumble", offsetof(Game::WeaponFullDef, weapDef.meleeImpactRumble), 0 },
		{ "tracerType", offsetof(Game::WeaponFullDef, weapDef.tracerType), 15 },
		{ "adsDofStart", offsetof(Game::WeaponFullDef, complete.adsDofStart), 7 },
		{ "adsDofEnd", offsetof(Game::WeaponFullDef, complete.adsDofEnd), 7 },
		{ "turretScopeZoomRate", offsetof(Game::WeaponFullDef, weapDef.turretScopeZoomRate), 7 },
		{ "turretScopeZoomMin", offsetof(Game::WeaponFullDef, weapDef.turretScopeZoomMin), 7 },
		{ "turretScopeZoomMax", offsetof(Game::WeaponFullDef, weapDef.turretScopeZoomMax), 7 },
		{ "thermalScope", offsetof(Game::WeaponFullDef, weapDef.thermalScope), 6 },
		{ "altModeSameWeapon", offsetof(Game::WeaponFullDef, weapDef.altModeSameWeapon), 6 },
		{ "turretOverheatUpRate", offsetof(Game::WeaponFullDef, weapDef.turretOverheatUpRate), 7 },
		{ "turretOverheatDownRate", offsetof(Game::WeaponFullDef, weapDef.turretOverheatDownRate), 7 },
		{ "turretOverheatPenalty", offsetof(Game::WeaponFullDef, weapDef.turretOverheatPenalty), 7 },
		{ "turretOverheatSound", offsetof(Game::WeaponFullDef, weapDef.turretOverheatSound), 14 },
		{ "turretOverheatEffect", offsetof(Game::WeaponFullDef, weapDef.turretOverheatEffect), 10 },
		{ "turretBarrelSpinEnabled", offsetof(Game::WeaponFullDef, weapDef.turretBarrelSpinEnabled), 6 },
		{ "turretBarrelSpinUpTime", offsetof(Game::WeaponFullDef, weapDef.turretBarrelSpinUpTime), 7 },
		{ "turretBarrelSpinDownTime", offsetof(Game::WeaponFullDef, weapDef.turretBarrelSpinDownTime), 7 },
		{ "turretBarrelSpinRumble", offsetof(Game::WeaponFullDef, weapDef.turretBarrelSpinRumble), 0 },
		{ "turretBarrelSpinSpeed", offsetof(Game::WeaponFullDef, weapDef.turretBarrelSpinSpeed), 7 },
		{ "turretBarrelSpinMaxSnd", offsetof(Game::WeaponFullDef, weapDef.turretBarrelSpinMaxSnd), 14 },
		{ "turretBarrelSpinUpSnd1", offsetof(Game::WeaponFullDef, weapDef.turretBarrelSpinUpSnd[0]), 14 },
		{ "turretBarrelSpinUpSnd2", offsetof(Game::WeaponFullDef, weapDef.turretBarrelSpinUpSnd[1]), 14 },
		{ "turretBarrelSpinUpSnd3", offsetof(Game::WeaponFullDef, weapDef.turretBarrelSpinUpSnd[2]), 14 },
		{ "turretBarrelSpinUpSnd4", offsetof(Game::WeaponFullDef, weapDef.turretBarrelSpinUpSnd[3]), 14 },
		{ "turretBarrelSpinDownSnd1", offsetof(Game::WeaponFullDef, weapDef.turretBarrelSpinDownSnd[0]), 14 },
		{ "turretBarrelSpinDownSnd2", offsetof(Game::WeaponFullDef, weapDef.turretBarrelSpinDownSnd[1]), 14 },
		{ "turretBarrelSpinDownSnd3", offsetof(Game::WeaponFullDef, weapDef.turretBarrelSpinDownSnd[2]), 14 },
		{ "turretBarrelSpinDownSnd4", offsetof(Game::WeaponFullDef, weapDef.turretBarrelSpinDownSnd[3]), 14 },
		{ "missileConeSoundEnabled", offsetof(Game::WeaponFullDef, weapDef.missileConeSoundEnabled), 6 },
		{ "missileConeSoundAlias", offsetof(Game::WeaponFullDef, weapDef.missileConeSoundAlias), 14 },
		{ "missileConeSoundAliasAtBase", offsetof(Game::WeaponFullDef, weapDef.missileConeSoundAliasAtBase), 14 },
		{ "missileConeSoundRadiusAtTop", offsetof(Game::WeaponFullDef, weapDef.missileConeSoundRadiusAtTop), 7 },
		{ "missileConeSoundRadiusAtBase", offsetof(Game::WeaponFullDef, weapDef.missileConeSoundRadiusAtBase), 7 },
		{ "missileConeSoundHeight", offsetof(Game::WeaponFullDef, weapDef.missileConeSoundHeight), 7 },
		{ "missileConeSoundOriginOffset", offsetof(Game::WeaponFullDef, weapDef.missileConeSoundOriginOffset), 7 },
		{ "missileConeSoundVolumescaleAtCore", offsetof(Game::WeaponFullDef, weapDef.missileConeSoundVolumescaleAtCore), 7 },
		{ "missileConeSoundVolumescaleAtEdge", offsetof(Game::WeaponFullDef, weapDef.missileConeSoundVolumescaleAtEdge), 7 },
		{ "missileConeSoundVolumescaleCoreSize", offsetof(Game::WeaponFullDef, weapDef.missileConeSoundVolumescaleCoreSize), 7 },
		{ "missileConeSoundPitchshiftEnabled", offsetof(Game::WeaponFullDef, weapDef.missileConeSoundPitchshiftEnabled), 6 },
		{ "missileConeSoundPitchAtTop", offsetof(Game::WeaponFullDef, weapDef.missileConeSoundPitchAtTop), 7 },
		{ "missileConeSoundPitchAtBottom", offsetof(Game::WeaponFullDef, weapDef.missileConeSoundPitchAtBottom), 7 },
		{ "missileConeSoundPitchTopSize", offsetof(Game::WeaponFullDef, weapDef.missileConeSoundPitchTopSize), 7 },
		{ "missileConeSoundPitchBottomSize", offsetof(Game::WeaponFullDef, weapDef.missileConeSoundPitchBottomSize), 7 },
		{ "missileConeSoundCrossfadeEnabled", offsetof(Game::WeaponFullDef, weapDef.missileConeSoundCrossfadeEnabled), 6 },
		{ "missileConeSoundCrossfadeTopSize", offsetof(Game::WeaponFullDef, weapDef.missileConeSoundCrossfadeTopSize), 7 },
		{ "missileConeSoundCrossfadeBottomSize", offsetof(Game::WeaponFullDef, weapDef.missileConeSoundCrossfadeBottomSize), 7 },
	};

	static constexpr std::size_t verifiedOffsets[] =
	{
		16, 160, 200, 240, 2712, 2720, 2728, 2736, 2744, 2752, 2760, 2768,
		2776, 2784, 2792, 2800, 2808, 2816, 2824, 2832, 176, 2352, 3432, 3496,
		2424, 2432, 2440, 2448, 2456, 2648, 2464, 2472, 2480, 2488, 2496, 2504,
		2512, 2520, 2544, 2528, 2536, 2552, 2560, 2568, 2576, 2584, 2592, 2600,
		2608, 2616, 2624, 2632, 2640, 2656, 2664, 2672, 2680, 2688, 2696, 2704,
		2848, 2856, 2864, 2872, 2880, 3072, 2888, 2896, 2904, 2912, 2920, 2928,
		2936, 2944, 2968, 2952, 2960, 2976, 2984, 2992, 3000, 3008, 3016, 3024,
		3032, 3040, 3048, 3056, 3064, 3080, 3088, 3096, 3104, 3112, 3120, 3128,
		3144, 3152, 3160, 3168, 3176, 3368, 3184, 3192, 3200, 3208, 3216, 3224,
		3232, 3240, 3264, 3248, 3256, 3272, 3280, 3288, 3296, 3304, 3312, 3320,
		3328, 3336, 3344, 3352, 3360, 3376, 3384, 3392, 3400, 3408, 3416, 3424,
		2016, 244, 248, 252, 68, 56, 256, 260, 264, 272, 280, 288,
		296, 304, 312, 320, 328, 336, 344, 352, 360, 368, 376, 384,
		392, 400, 408, 416, 424, 432, 440, 448, 456, 464, 472, 480,
		488, 496, 504, 512, 520, 528, 536, 544, 552, 560, 568, 576,
		584, 608, 616, 624, 632, 592, 600, 640, 648, 656, 664, 672,
		680, 688, 696, 704, 712, 720, 724, 728, 732, 736, 740, 744,
		748, 752, 756, 760, 764, 768, 772, 776, 780, 784, 788, 792,
		796, 800, 804, 808, 812, 816, 820, 824, 828, 832, 836, 840,
		844, 848, 852, 856, 860, 864, 868, 872, 876, 880, 884, 888,
		892, 3560, 3568, 3576, 3584, 3592, 3600, 3608, 3616, 3624, 3632, 3640,
		3648, 3656, 3664, 3672, 3680, 904, 912, 920, 928, 936, 944, 952,
		960, 968, 976, 980, 984, 2300, 992, 1008, 1020, 52, 1024, 1032,
		1044, 1048, 1052, 1056, 2032, 2036, 2040, 2044, 2048, 2052, 2056, 1064,
		1068, 1072, 60, 1080, 1084, 1088, 1092, 1096, 1076, 1100, 1104, 1108,
		1112, 1116, 1120, 1124, 1128, 1132, 1136, 1140, 1144, 92, 1148, 1152,
		116, 1156, 1160, 1164, 1168, 1172, 1176, 1180, 1184, 1188, 1192, 1196,
		1200, 1204, 1208, 1212, 1216, 1220, 2301, 2302, 2303, 2304, 2306, 2305,
		1224, 1228, 1232, 1236, 1240, 2307, 1244, 1248, 1252, 1396, 1400, 1404,
		1408, 1412, 1416, 1420, 1424, 1428, 1432, 1436, 1440, 1444, 1448, 1452,
		1456, 1460, 2308, 2309, 2310, 2311, 2312, 2313, 1464, 1468, 2315, 2316,
		2314, 2317, 2318, 2319, 2320, 153, 152, 2321, 2322, 1472, 2323, 1480,
		96, 1484, 2324, 104, 64, 154, 2325, 2326, 1488, 1492, 80, 1496,
		120, 1500, 1504, 2327, 2328, 2329, 1508, 1512, 1516, 1520, 1524, 1528,
		1532, 1536, 1540, 1544, 1548, 1552, 1556, 1560, 1568, 1576, 1584, 2330,
		1600, 1592, 1608, 2331, 1616, 2332, 2333, 2334, 2335, 2336, 2337, 2338,
		1620, 1624, 2345, 3688, 3692, 3696, 3700, 3704, 3708, 3712, 3716, 3720,
		3724, 3728, 3732, 3736, 3740, 3744, 3748, 3752, 3756, 3760, 3764, 3768,
		3772, 3776, 3780, 3784, 3788, 3792, 3796, 3800, 3804, 3808, 3812, 3816,
		3820, 3824, 3828, 3832, 3836, 3840, 3844, 3848, 3852, 3856, 3860, 3864,
		3868, 3872, 3876, 3880, 3884, 3888, 3892, 3896, 3900, 3780, 3784, 3788,
		3916, 3920, 3924, 3928, 3932, 1648, 1656, 1664, 1668, 1672, 1676, 1680,
		1684, 1688, 1696, 44, 48, 1380, 1388, 40, 1256, 1260, 1264, 1272,
		1280, 1288, 1296, 1300, 1304, 1308, 1312, 1316, 1320, 1324, 1704, 1708,
		1712, 1892, 1716, 1720, 1724, 1728, 1732, 1736, 1740, 1744, 1748, 1752,
		1756, 1760, 1764, 1768, 72, 1780, 1676, 1328, 1332, 1336, 1340, 1344,
		1348, 1352, 1356, 1360, 1364, 1368, 1372, 1376, 1384, 1392, 1784, 1788,
		1792, 1796, 1800, 1804, 1808, 1812, 1816, 1820, 1824, 1828, 1832, 1836,
		76, 1896, 1900, 1904, 1908, 1912, 1916, 1920, 1932, 1936, 1924, 1928,
		1940, 1944, 1948, 1952, 1956, 1960, 268, 1968, 1976, 1992, 1996, 2000,
		2004, 2008, 1848, 1852, 1856, 1864, 3936, 3940, 3944, 3948, 3952, 3956,
		3960, 3968, 3976, 3964, 3972, 3980, 3984, 3992, 4000, 3988, 3996, 4004,
		4008, 2072, 2080, 2088, 124, 128, 2096, 2100, 2104, 2339, 2340, 2108,
		2112, 2116, 2120, 2128, 2341, 2148, 2152, 2136, 2144, 2160, 2168, 2176,
		2184, 2192, 2200, 2208, 2216, 2224, 2342, 2232, 2240, 2248, 2252, 2256,
		2260, 2264, 2268, 2272, 2343, 2276, 2280, 2284, 2288, 2344, 2292, 2296,
	};

	static_assert(std::size(weaponFields) == std::size(verifiedOffsets));

	constexpr bool WeaponFieldOffsetsMatch()
	{
		for (std::size_t i = 0; i < std::size(weaponFields); ++i)
		{
			if (weaponFields[i].offset != verifiedOffsets[i])
			{
				return false;
			}
		}

		return true;
	}

	static_assert(WeaponFieldOffsetsMatch(), "a weapon field does not land where the verified x64 layout puts it");
}
