#ifndef GOOGLE_PROTOBUF_INCLUDED_auth_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_auth_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_auth_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}
PROTOBUF_NAMESPACE_CLOSE

struct TableStruct_auth_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_auth_2eproto;
namespace Proto {
namespace Auth {
class Certificate;
struct CertificateDefaultTypeInternal;
extern CertificateDefaultTypeInternal _Certificate_default_instance_;
class Connect;
struct ConnectDefaultTypeInternal;
extern ConnectDefaultTypeInternal _Connect_default_instance_;
}
}
PROTOBUF_NAMESPACE_OPEN
template<> ::Proto::Auth::Certificate* Arena::CreateMaybeMessage<::Proto::Auth::Certificate>(Arena*);
template<> ::Proto::Auth::Connect* Arena::CreateMaybeMessage<::Proto::Auth::Connect>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Proto {
namespace Auth {

class Certificate final :
    public ::PROTOBUF_NAMESPACE_ID::Message  {
 public:
  inline Certificate() : Certificate(nullptr) {}
  ~Certificate() override;
  explicit PROTOBUF_CONSTEXPR Certificate(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Certificate(const Certificate& from);
  Certificate(Certificate&& from) noexcept
    : Certificate() {
    *this = ::std::move(from);
  }

  inline Certificate& operator=(const Certificate& from) {
    CopyFrom(from);
    return *this;
  }
  inline Certificate& operator=(Certificate&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Certificate& default_instance() {
    return *internal_default_instance();
  }
  static inline const Certificate* internal_default_instance() {
    return reinterpret_cast<const Certificate*>(
               &_Certificate_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Certificate& a, Certificate& b) {
    a.Swap(&b);
  }
  inline void Swap(Certificate* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Certificate* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  Certificate* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Certificate>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Certificate& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Certificate& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Certificate* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Proto.Auth.Certificate";
  }
  protected:
  explicit Certificate(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  enum : int {
    kPrivatekeyFieldNumber = 1,
    kTokenFieldNumber = 2,
    kCtokenFieldNumber = 3,
  };
  void clear_privatekey();
  const std::string& privatekey() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_privatekey(ArgT0&& arg0, ArgT... args);
  std::string* mutable_privatekey();
  PROTOBUF_NODISCARD std::string* release_privatekey();
  void set_allocated_privatekey(std::string* privatekey);
  private:
  const std::string& _internal_privatekey() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_privatekey(const std::string& value);
  std::string* _internal_mutable_privatekey();
  public:

  void clear_token();
  const std::string& token() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_token(ArgT0&& arg0, ArgT... args);
  std::string* mutable_token();
  PROTOBUF_NODISCARD std::string* release_token();
  void set_allocated_token(std::string* token);
  private:
  const std::string& _internal_token() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_token(const std::string& value);
  std::string* _internal_mutable_token();
  public:

  void clear_ctoken();
  const std::string& ctoken() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_ctoken(ArgT0&& arg0, ArgT... args);
  std::string* mutable_ctoken();
  PROTOBUF_NODISCARD std::string* release_ctoken();
  void set_allocated_ctoken(std::string* ctoken);
  private:
  const std::string& _internal_ctoken() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ctoken(const std::string& value);
  std::string* _internal_mutable_ctoken();
  public:

 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr privatekey_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr token_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ctoken_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_auth_2eproto;
};

class Connect final :
    public ::PROTOBUF_NAMESPACE_ID::Message  {
 public:
  inline Connect() : Connect(nullptr) {}
  ~Connect() override;
  explicit PROTOBUF_CONSTEXPR Connect(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Connect(const Connect& from);
  Connect(Connect&& from) noexcept
    : Connect() {
    *this = ::std::move(from);
  }

  inline Connect& operator=(const Connect& from) {
    CopyFrom(from);
    return *this;
  }
  inline Connect& operator=(Connect&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Connect& default_instance() {
    return *internal_default_instance();
  }
  static inline const Connect* internal_default_instance() {
    return reinterpret_cast<const Connect*>(
               &_Connect_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Connect& a, Connect& b) {
    a.Swap(&b);
  }
  inline void Swap(Connect* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Connect* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  Connect* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Connect>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Connect& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Connect& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Connect* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Proto.Auth.Connect";
  }
  protected:
  explicit Connect(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  enum : int {
    kSignatureFieldNumber = 1,
    kPublickeyFieldNumber = 2,
    kTokenFieldNumber = 3,
    kInfostringFieldNumber = 4,
    kConnectTicketFieldNumber = 5,
    kMatchIdFieldNumber = 6,
    kSessionIdFieldNumber = 7,
  };
  void clear_signature();
  const std::string& signature() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_signature(ArgT0&& arg0, ArgT... args);
  std::string* mutable_signature();
  PROTOBUF_NODISCARD std::string* release_signature();
  void set_allocated_signature(std::string* signature);
  private:
  const std::string& _internal_signature() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_signature(const std::string& value);
  std::string* _internal_mutable_signature();
  public:

  void clear_publickey();
  const std::string& publickey() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_publickey(ArgT0&& arg0, ArgT... args);
  std::string* mutable_publickey();
  PROTOBUF_NODISCARD std::string* release_publickey();
  void set_allocated_publickey(std::string* publickey);
  private:
  const std::string& _internal_publickey() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_publickey(const std::string& value);
  std::string* _internal_mutable_publickey();
  public:

  void clear_token();
  const std::string& token() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_token(ArgT0&& arg0, ArgT... args);
  std::string* mutable_token();
  PROTOBUF_NODISCARD std::string* release_token();
  void set_allocated_token(std::string* token);
  private:
  const std::string& _internal_token() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_token(const std::string& value);
  std::string* _internal_mutable_token();
  public:

  void clear_infostring();
  const std::string& infostring() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_infostring(ArgT0&& arg0, ArgT... args);
  std::string* mutable_infostring();
  PROTOBUF_NODISCARD std::string* release_infostring();
  void set_allocated_infostring(std::string* infostring);
  private:
  const std::string& _internal_infostring() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_infostring(const std::string& value);
  std::string* _internal_mutable_infostring();
  public:

  void clear_connect_ticket();
  const std::string& connect_ticket() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_connect_ticket(ArgT0&& arg0, ArgT... args);
  std::string* mutable_connect_ticket();
  PROTOBUF_NODISCARD std::string* release_connect_ticket();
  void set_allocated_connect_ticket(std::string* connect_ticket);
  private:
  const std::string& _internal_connect_ticket() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_connect_ticket(const std::string& value);
  std::string* _internal_mutable_connect_ticket();
  public:

  void clear_match_id();
  const std::string& match_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_match_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_match_id();
  PROTOBUF_NODISCARD std::string* release_match_id();
  void set_allocated_match_id(std::string* match_id);
  private:
  const std::string& _internal_match_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_match_id(const std::string& value);
  std::string* _internal_mutable_match_id();
  public:

  void clear_session_id();
  const std::string& session_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_session_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_session_id();
  PROTOBUF_NODISCARD std::string* release_session_id();
  void set_allocated_session_id(std::string* session_id);
  private:
  const std::string& _internal_session_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_session_id(const std::string& value);
  std::string* _internal_mutable_session_id();
  public:

 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr signature_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr publickey_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr token_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr infostring_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr connect_ticket_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr match_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr session_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_auth_2eproto;
};


#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

inline void Certificate::clear_privatekey() {
  privatekey_.ClearToEmpty();
}
inline const std::string& Certificate::privatekey() const {
  return _internal_privatekey();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Certificate::set_privatekey(ArgT0&& arg0, ArgT... args) {
 
 privatekey_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
}
inline std::string* Certificate::mutable_privatekey() {
  std::string* _s = _internal_mutable_privatekey();
  return _s;
}
inline const std::string& Certificate::_internal_privatekey() const {
  return privatekey_.Get();
}
inline void Certificate::_internal_set_privatekey(const std::string& value) {
  
  privatekey_.Set(value, GetArenaForAllocation());
}
inline std::string* Certificate::_internal_mutable_privatekey() {
  
  return privatekey_.Mutable(GetArenaForAllocation());
}
inline std::string* Certificate::release_privatekey() {
  return privatekey_.Release();
}
inline void Certificate::set_allocated_privatekey(std::string* privatekey) {
  if (privatekey != nullptr) {
    
  } else {
    
  }
  privatekey_.SetAllocated(privatekey, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (privatekey_.IsDefault()) {
    privatekey_.Set("", GetArenaForAllocation());
  }
#endif
}

inline void Certificate::clear_token() {
  token_.ClearToEmpty();
}
inline const std::string& Certificate::token() const {
  return _internal_token();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Certificate::set_token(ArgT0&& arg0, ArgT... args) {
 
 token_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
}
inline std::string* Certificate::mutable_token() {
  std::string* _s = _internal_mutable_token();
  return _s;
}
inline const std::string& Certificate::_internal_token() const {
  return token_.Get();
}
inline void Certificate::_internal_set_token(const std::string& value) {
  
  token_.Set(value, GetArenaForAllocation());
}
inline std::string* Certificate::_internal_mutable_token() {
  
  return token_.Mutable(GetArenaForAllocation());
}
inline std::string* Certificate::release_token() {
  return token_.Release();
}
inline void Certificate::set_allocated_token(std::string* token) {
  if (token != nullptr) {
    
  } else {
    
  }
  token_.SetAllocated(token, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (token_.IsDefault()) {
    token_.Set("", GetArenaForAllocation());
  }
#endif
}

inline void Certificate::clear_ctoken() {
  ctoken_.ClearToEmpty();
}
inline const std::string& Certificate::ctoken() const {
  return _internal_ctoken();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Certificate::set_ctoken(ArgT0&& arg0, ArgT... args) {
 
 ctoken_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
}
inline std::string* Certificate::mutable_ctoken() {
  std::string* _s = _internal_mutable_ctoken();
  return _s;
}
inline const std::string& Certificate::_internal_ctoken() const {
  return ctoken_.Get();
}
inline void Certificate::_internal_set_ctoken(const std::string& value) {
  
  ctoken_.Set(value, GetArenaForAllocation());
}
inline std::string* Certificate::_internal_mutable_ctoken() {
  
  return ctoken_.Mutable(GetArenaForAllocation());
}
inline std::string* Certificate::release_ctoken() {
  return ctoken_.Release();
}
inline void Certificate::set_allocated_ctoken(std::string* ctoken) {
  if (ctoken != nullptr) {
    
  } else {
    
  }
  ctoken_.SetAllocated(ctoken, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (ctoken_.IsDefault()) {
    ctoken_.Set("", GetArenaForAllocation());
  }
#endif
}

inline void Connect::clear_signature() {
  signature_.ClearToEmpty();
}
inline const std::string& Connect::signature() const {
  return _internal_signature();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Connect::set_signature(ArgT0&& arg0, ArgT... args) {
 
 signature_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
}
inline std::string* Connect::mutable_signature() {
  std::string* _s = _internal_mutable_signature();
  return _s;
}
inline const std::string& Connect::_internal_signature() const {
  return signature_.Get();
}
inline void Connect::_internal_set_signature(const std::string& value) {
  
  signature_.Set(value, GetArenaForAllocation());
}
inline std::string* Connect::_internal_mutable_signature() {
  
  return signature_.Mutable(GetArenaForAllocation());
}
inline std::string* Connect::release_signature() {
  return signature_.Release();
}
inline void Connect::set_allocated_signature(std::string* signature) {
  if (signature != nullptr) {
    
  } else {
    
  }
  signature_.SetAllocated(signature, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (signature_.IsDefault()) {
    signature_.Set("", GetArenaForAllocation());
  }
#endif
}

inline void Connect::clear_publickey() {
  publickey_.ClearToEmpty();
}
inline const std::string& Connect::publickey() const {
  return _internal_publickey();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Connect::set_publickey(ArgT0&& arg0, ArgT... args) {
 
 publickey_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
}
inline std::string* Connect::mutable_publickey() {
  std::string* _s = _internal_mutable_publickey();
  return _s;
}
inline const std::string& Connect::_internal_publickey() const {
  return publickey_.Get();
}
inline void Connect::_internal_set_publickey(const std::string& value) {
  
  publickey_.Set(value, GetArenaForAllocation());
}
inline std::string* Connect::_internal_mutable_publickey() {
  
  return publickey_.Mutable(GetArenaForAllocation());
}
inline std::string* Connect::release_publickey() {
  return publickey_.Release();
}
inline void Connect::set_allocated_publickey(std::string* publickey) {
  if (publickey != nullptr) {
    
  } else {
    
  }
  publickey_.SetAllocated(publickey, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (publickey_.IsDefault()) {
    publickey_.Set("", GetArenaForAllocation());
  }
#endif
}

inline void Connect::clear_token() {
  token_.ClearToEmpty();
}
inline const std::string& Connect::token() const {
  return _internal_token();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Connect::set_token(ArgT0&& arg0, ArgT... args) {
 
 token_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
}
inline std::string* Connect::mutable_token() {
  std::string* _s = _internal_mutable_token();
  return _s;
}
inline const std::string& Connect::_internal_token() const {
  return token_.Get();
}
inline void Connect::_internal_set_token(const std::string& value) {
  
  token_.Set(value, GetArenaForAllocation());
}
inline std::string* Connect::_internal_mutable_token() {
  
  return token_.Mutable(GetArenaForAllocation());
}
inline std::string* Connect::release_token() {
  return token_.Release();
}
inline void Connect::set_allocated_token(std::string* token) {
  if (token != nullptr) {
    
  } else {
    
  }
  token_.SetAllocated(token, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (token_.IsDefault()) {
    token_.Set("", GetArenaForAllocation());
  }
#endif
}

inline void Connect::clear_infostring() {
  infostring_.ClearToEmpty();
}
inline const std::string& Connect::infostring() const {
  return _internal_infostring();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Connect::set_infostring(ArgT0&& arg0, ArgT... args) {
 
 infostring_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
}
inline std::string* Connect::mutable_infostring() {
  std::string* _s = _internal_mutable_infostring();
  return _s;
}
inline const std::string& Connect::_internal_infostring() const {
  return infostring_.Get();
}
inline void Connect::_internal_set_infostring(const std::string& value) {
  
  infostring_.Set(value, GetArenaForAllocation());
}
inline std::string* Connect::_internal_mutable_infostring() {
  
  return infostring_.Mutable(GetArenaForAllocation());
}
inline std::string* Connect::release_infostring() {
  return infostring_.Release();
}
inline void Connect::set_allocated_infostring(std::string* infostring) {
  if (infostring != nullptr) {
    
  } else {
    
  }
  infostring_.SetAllocated(infostring, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (infostring_.IsDefault()) {
    infostring_.Set("", GetArenaForAllocation());
  }
#endif
}

inline void Connect::clear_connect_ticket() {
  connect_ticket_.ClearToEmpty();
}
inline const std::string& Connect::connect_ticket() const {
  return _internal_connect_ticket();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Connect::set_connect_ticket(ArgT0&& arg0, ArgT... args) {
 
 connect_ticket_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
}
inline std::string* Connect::mutable_connect_ticket() {
  std::string* _s = _internal_mutable_connect_ticket();
  return _s;
}
inline const std::string& Connect::_internal_connect_ticket() const {
  return connect_ticket_.Get();
}
inline void Connect::_internal_set_connect_ticket(const std::string& value) {
  
  connect_ticket_.Set(value, GetArenaForAllocation());
}
inline std::string* Connect::_internal_mutable_connect_ticket() {
  
  return connect_ticket_.Mutable(GetArenaForAllocation());
}
inline std::string* Connect::release_connect_ticket() {
  return connect_ticket_.Release();
}
inline void Connect::set_allocated_connect_ticket(std::string* connect_ticket) {
  if (connect_ticket != nullptr) {
    
  } else {
    
  }
  connect_ticket_.SetAllocated(connect_ticket, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (connect_ticket_.IsDefault()) {
    connect_ticket_.Set("", GetArenaForAllocation());
  }
#endif
}

inline void Connect::clear_match_id() {
  match_id_.ClearToEmpty();
}
inline const std::string& Connect::match_id() const {
  return _internal_match_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Connect::set_match_id(ArgT0&& arg0, ArgT... args) {
 
 match_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
}
inline std::string* Connect::mutable_match_id() {
  std::string* _s = _internal_mutable_match_id();
  return _s;
}
inline const std::string& Connect::_internal_match_id() const {
  return match_id_.Get();
}
inline void Connect::_internal_set_match_id(const std::string& value) {
  
  match_id_.Set(value, GetArenaForAllocation());
}
inline std::string* Connect::_internal_mutable_match_id() {
  
  return match_id_.Mutable(GetArenaForAllocation());
}
inline std::string* Connect::release_match_id() {
  return match_id_.Release();
}
inline void Connect::set_allocated_match_id(std::string* match_id) {
  if (match_id != nullptr) {
    
  } else {
    
  }
  match_id_.SetAllocated(match_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (match_id_.IsDefault()) {
    match_id_.Set("", GetArenaForAllocation());
  }
#endif
}

inline void Connect::clear_session_id() {
  session_id_.ClearToEmpty();
}
inline const std::string& Connect::session_id() const {
  return _internal_session_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Connect::set_session_id(ArgT0&& arg0, ArgT... args) {
 
 session_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
}
inline std::string* Connect::mutable_session_id() {
  std::string* _s = _internal_mutable_session_id();
  return _s;
}
inline const std::string& Connect::_internal_session_id() const {
  return session_id_.Get();
}
inline void Connect::_internal_set_session_id(const std::string& value) {
  
  session_id_.Set(value, GetArenaForAllocation());
}
inline std::string* Connect::_internal_mutable_session_id() {
  
  return session_id_.Mutable(GetArenaForAllocation());
}
inline std::string* Connect::release_session_id() {
  return session_id_.Release();
}
inline void Connect::set_allocated_session_id(std::string* session_id) {
  if (session_id != nullptr) {
    
  } else {
    
  }
  session_id_.SetAllocated(session_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (session_id_.IsDefault()) {
    session_id_.Set("", GetArenaForAllocation());
  }
#endif
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif


}
}

#include <google/protobuf/port_undef.inc>
#endif
