#ifndef GOOGLE_PROTOBUF_INCLUDED_friends_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_friends_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_friends_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}
PROTOBUF_NAMESPACE_CLOSE

struct TableStruct_friends_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_friends_2eproto;
namespace Proto {
namespace Friends {
class Friend;
struct FriendDefaultTypeInternal;
extern FriendDefaultTypeInternal _Friend_default_instance_;
class List;
struct ListDefaultTypeInternal;
extern ListDefaultTypeInternal _List_default_instance_;
}
}
PROTOBUF_NAMESPACE_OPEN
template<> ::Proto::Friends::Friend* Arena::CreateMaybeMessage<::Proto::Friends::Friend>(Arena*);
template<> ::Proto::Friends::List* Arena::CreateMaybeMessage<::Proto::Friends::List>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Proto {
namespace Friends {

class Friend final :
    public ::PROTOBUF_NAMESPACE_ID::Message  {
 public:
  inline Friend() : Friend(nullptr) {}
  ~Friend() override;
  explicit PROTOBUF_CONSTEXPR Friend(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Friend(const Friend& from);
  Friend(Friend&& from) noexcept
    : Friend() {
    *this = ::std::move(from);
  }

  inline Friend& operator=(const Friend& from) {
    CopyFrom(from);
    return *this;
  }
  inline Friend& operator=(Friend&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Friend& default_instance() {
    return *internal_default_instance();
  }
  static inline const Friend* internal_default_instance() {
    return reinterpret_cast<const Friend*>(
               &_Friend_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Friend& a, Friend& b) {
    a.Swap(&b);
  }
  inline void Swap(Friend* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Friend* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  Friend* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Friend>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Friend& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Friend& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Friend* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Proto.Friends.Friend";
  }
  protected:
  explicit Friend(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  enum : int {
    kSteamidFieldNumber = 1,
    kNameFieldNumber = 2,
    kGuidFieldNumber = 3,
    kPrestigeFieldNumber = 4,
    kExperienceFieldNumber = 5,
  };
  void clear_steamid();
  const std::string& steamid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_steamid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_steamid();
  PROTOBUF_NODISCARD std::string* release_steamid();
  void set_allocated_steamid(std::string* steamid);
  private:
  const std::string& _internal_steamid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_steamid(const std::string& value);
  std::string* _internal_mutable_steamid();
  public:

  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  void clear_guid();
  const std::string& guid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_guid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_guid();
  PROTOBUF_NODISCARD std::string* release_guid();
  void set_allocated_guid(std::string* guid);
  private:
  const std::string& _internal_guid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_guid(const std::string& value);
  std::string* _internal_mutable_guid();
  public:

  void clear_prestige();
  uint32_t prestige() const;
  void set_prestige(uint32_t value);
  private:
  uint32_t _internal_prestige() const;
  void _internal_set_prestige(uint32_t value);
  public:

  void clear_experience();
  uint32_t experience() const;
  void set_experience(uint32_t value);
  private:
  uint32_t _internal_experience() const;
  void _internal_set_experience(uint32_t value);
  public:

 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr steamid_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr guid_;
  uint32_t prestige_;
  uint32_t experience_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_friends_2eproto;
};

class List final :
    public ::PROTOBUF_NAMESPACE_ID::Message  {
 public:
  inline List() : List(nullptr) {}
  ~List() override;
  explicit PROTOBUF_CONSTEXPR List(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  List(const List& from);
  List(List&& from) noexcept
    : List() {
    *this = ::std::move(from);
  }

  inline List& operator=(const List& from) {
    CopyFrom(from);
    return *this;
  }
  inline List& operator=(List&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const List& default_instance() {
    return *internal_default_instance();
  }
  static inline const List* internal_default_instance() {
    return reinterpret_cast<const List*>(
               &_List_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(List& a, List& b) {
    a.Swap(&b);
  }
  inline void Swap(List* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(List* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  List* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<List>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const List& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const List& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(List* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Proto.Friends.List";
  }
  protected:
  explicit List(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  enum : int {
    kFriendsFieldNumber = 1,
  };
  int friends_size() const;
  private:
  int _internal_friends_size() const;
  public:
  void clear_friends();
  ::Proto::Friends::Friend* mutable_friends(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Proto::Friends::Friend >*
      mutable_friends();
  private:
  const ::Proto::Friends::Friend& _internal_friends(int index) const;
  ::Proto::Friends::Friend* _internal_add_friends();
  public:
  const ::Proto::Friends::Friend& friends(int index) const;
  ::Proto::Friends::Friend* add_friends();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Proto::Friends::Friend >&
      friends() const;

 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Proto::Friends::Friend > friends_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_friends_2eproto;
};


#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

inline void Friend::clear_steamid() {
  steamid_.ClearToEmpty();
}
inline const std::string& Friend::steamid() const {
  return _internal_steamid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Friend::set_steamid(ArgT0&& arg0, ArgT... args) {
 
 steamid_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
}
inline std::string* Friend::mutable_steamid() {
  std::string* _s = _internal_mutable_steamid();
  return _s;
}
inline const std::string& Friend::_internal_steamid() const {
  return steamid_.Get();
}
inline void Friend::_internal_set_steamid(const std::string& value) {
  
  steamid_.Set(value, GetArenaForAllocation());
}
inline std::string* Friend::_internal_mutable_steamid() {
  
  return steamid_.Mutable(GetArenaForAllocation());
}
inline std::string* Friend::release_steamid() {
  return steamid_.Release();
}
inline void Friend::set_allocated_steamid(std::string* steamid) {
  if (steamid != nullptr) {
    
  } else {
    
  }
  steamid_.SetAllocated(steamid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (steamid_.IsDefault()) {
    steamid_.Set("", GetArenaForAllocation());
  }
#endif
}

inline void Friend::clear_name() {
  name_.ClearToEmpty();
}
inline const std::string& Friend::name() const {
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Friend::set_name(ArgT0&& arg0, ArgT... args) {
 
 name_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
}
inline std::string* Friend::mutable_name() {
  std::string* _s = _internal_mutable_name();
  return _s;
}
inline const std::string& Friend::_internal_name() const {
  return name_.Get();
}
inline void Friend::_internal_set_name(const std::string& value) {
  
  name_.Set(value, GetArenaForAllocation());
}
inline std::string* Friend::_internal_mutable_name() {
  
  return name_.Mutable(GetArenaForAllocation());
}
inline std::string* Friend::release_name() {
  return name_.Release();
}
inline void Friend::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (name_.IsDefault()) {
    name_.Set("", GetArenaForAllocation());
  }
#endif
}

inline void Friend::clear_guid() {
  guid_.ClearToEmpty();
}
inline const std::string& Friend::guid() const {
  return _internal_guid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Friend::set_guid(ArgT0&& arg0, ArgT... args) {
 
 guid_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
}
inline std::string* Friend::mutable_guid() {
  std::string* _s = _internal_mutable_guid();
  return _s;
}
inline const std::string& Friend::_internal_guid() const {
  return guid_.Get();
}
inline void Friend::_internal_set_guid(const std::string& value) {
  
  guid_.Set(value, GetArenaForAllocation());
}
inline std::string* Friend::_internal_mutable_guid() {
  
  return guid_.Mutable(GetArenaForAllocation());
}
inline std::string* Friend::release_guid() {
  return guid_.Release();
}
inline void Friend::set_allocated_guid(std::string* guid) {
  if (guid != nullptr) {
    
  } else {
    
  }
  guid_.SetAllocated(guid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (guid_.IsDefault()) {
    guid_.Set("", GetArenaForAllocation());
  }
#endif
}

inline void Friend::clear_prestige() {
  prestige_ = 0u;
}
inline uint32_t Friend::_internal_prestige() const {
  return prestige_;
}
inline uint32_t Friend::prestige() const {
  return _internal_prestige();
}
inline void Friend::_internal_set_prestige(uint32_t value) {
  
  prestige_ = value;
}
inline void Friend::set_prestige(uint32_t value) {
  _internal_set_prestige(value);
}

inline void Friend::clear_experience() {
  experience_ = 0u;
}
inline uint32_t Friend::_internal_experience() const {
  return experience_;
}
inline uint32_t Friend::experience() const {
  return _internal_experience();
}
inline void Friend::_internal_set_experience(uint32_t value) {
  
  experience_ = value;
}
inline void Friend::set_experience(uint32_t value) {
  _internal_set_experience(value);
}

inline int List::_internal_friends_size() const {
  return friends_.size();
}
inline int List::friends_size() const {
  return _internal_friends_size();
}
inline void List::clear_friends() {
  friends_.Clear();
}
inline ::Proto::Friends::Friend* List::mutable_friends(int index) {
  return friends_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Proto::Friends::Friend >*
List::mutable_friends() {
  return &friends_;
}
inline const ::Proto::Friends::Friend& List::_internal_friends(int index) const {
  return friends_.Get(index);
}
inline const ::Proto::Friends::Friend& List::friends(int index) const {
  return _internal_friends(index);
}
inline ::Proto::Friends::Friend* List::_internal_add_friends() {
  return friends_.Add();
}
inline ::Proto::Friends::Friend* List::add_friends() {
  ::Proto::Friends::Friend* _add = _internal_add_friends();
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Proto::Friends::Friend >&
List::friends() const {
  return friends_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif


}
}

#include <google/protobuf/port_undef.inc>
#endif
