#ifndef GOOGLE_PROTOBUF_INCLUDED_node_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_node_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_node_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}
PROTOBUF_NAMESPACE_CLOSE

struct TableStruct_node_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_node_2eproto;
namespace Proto {
namespace Node {
class List;
struct ListDefaultTypeInternal;
extern ListDefaultTypeInternal _List_default_instance_;
}
}
PROTOBUF_NAMESPACE_OPEN
template<> ::Proto::Node::List* Arena::CreateMaybeMessage<::Proto::Node::List>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Proto {
namespace Node {

class List final :
    public ::PROTOBUF_NAMESPACE_ID::Message  {
 public:
  inline List() : List(nullptr) {}
  ~List() override;
  explicit PROTOBUF_CONSTEXPR List(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  List(const List& from);
  List(List&& from) noexcept
    : List() {
    *this = ::std::move(from);
  }

  inline List& operator=(const List& from) {
    CopyFrom(from);
    return *this;
  }
  inline List& operator=(List&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const List& default_instance() {
    return *internal_default_instance();
  }
  static inline const List* internal_default_instance() {
    return reinterpret_cast<const List*>(
               &_List_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(List& a, List& b) {
    a.Swap(&b);
  }
  inline void Swap(List* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(List* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  List* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<List>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const List& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const List& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(List* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Proto.Node.List";
  }
  protected:
  explicit List(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  enum : int {
    kNodesFieldNumber = 1,
    kPortFieldNumber = 2,
    kIsNodeFieldNumber = 3,
    kProtocolFieldNumber = 4,
  };
  int nodes_size() const;
  private:
  int _internal_nodes_size() const;
  public:
  void clear_nodes();
  const std::string& nodes(int index) const;
  std::string* mutable_nodes(int index);
  void set_nodes(int index, const std::string& value);
  void set_nodes(int index, std::string&& value);
  void set_nodes(int index, const char* value);
  void set_nodes(int index, const void* value, size_t size);
  std::string* add_nodes();
  void add_nodes(const std::string& value);
  void add_nodes(std::string&& value);
  void add_nodes(const char* value);
  void add_nodes(const void* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& nodes() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_nodes();
  private:
  const std::string& _internal_nodes(int index) const;
  std::string* _internal_add_nodes();
  public:

  void clear_port();
  uint32_t port() const;
  void set_port(uint32_t value);
  private:
  uint32_t _internal_port() const;
  void _internal_set_port(uint32_t value);
  public:

  void clear_isnode();
  bool isnode() const;
  void set_isnode(bool value);
  private:
  bool _internal_isnode() const;
  void _internal_set_isnode(bool value);
  public:

  void clear_protocol();
  uint64_t protocol() const;
  void set_protocol(uint64_t value);
  private:
  uint64_t _internal_protocol() const;
  void _internal_set_protocol(uint64_t value);
  public:

 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> nodes_;
  uint32_t port_;
  bool isnode_;
  uint64_t protocol_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_node_2eproto;
};


#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

inline int List::_internal_nodes_size() const {
  return nodes_.size();
}
inline int List::nodes_size() const {
  return _internal_nodes_size();
}
inline void List::clear_nodes() {
  nodes_.Clear();
}
inline std::string* List::add_nodes() {
  std::string* _s = _internal_add_nodes();
  return _s;
}
inline const std::string& List::_internal_nodes(int index) const {
  return nodes_.Get(index);
}
inline const std::string& List::nodes(int index) const {
  return _internal_nodes(index);
}
inline std::string* List::mutable_nodes(int index) {
  return nodes_.Mutable(index);
}
inline void List::set_nodes(int index, const std::string& value) {
  nodes_.Mutable(index)->assign(value);
}
inline void List::set_nodes(int index, std::string&& value) {
  nodes_.Mutable(index)->assign(std::move(value));
}
inline void List::set_nodes(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  nodes_.Mutable(index)->assign(value);
}
inline void List::set_nodes(int index, const void* value, size_t size) {
  nodes_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline std::string* List::_internal_add_nodes() {
  return nodes_.Add();
}
inline void List::add_nodes(const std::string& value) {
  nodes_.Add()->assign(value);
}
inline void List::add_nodes(std::string&& value) {
  nodes_.Add(std::move(value));
}
inline void List::add_nodes(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  nodes_.Add()->assign(value);
}
inline void List::add_nodes(const void* value, size_t size) {
  nodes_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
List::nodes() const {
  return nodes_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
List::mutable_nodes() {
  return &nodes_;
}

inline void List::clear_port() {
  port_ = 0u;
}
inline uint32_t List::_internal_port() const {
  return port_;
}
inline uint32_t List::port() const {
  return _internal_port();
}
inline void List::_internal_set_port(uint32_t value) {
  
  port_ = value;
}
inline void List::set_port(uint32_t value) {
  _internal_set_port(value);
}

inline void List::clear_isnode() {
  isnode_ = false;
}
inline bool List::_internal_isnode() const {
  return isnode_;
}
inline bool List::isnode() const {
  return _internal_isnode();
}
inline void List::_internal_set_isnode(bool value) {
  
  isnode_ = value;
}
inline void List::set_isnode(bool value) {
  _internal_set_isnode(value);
}

inline void List::clear_protocol() {
  protocol_ = uint64_t{0u};
}
inline uint64_t List::_internal_protocol() const {
  return protocol_;
}
inline uint64_t List::protocol() const {
  return _internal_protocol();
}
inline void List::_internal_set_protocol(uint64_t value) {
  
  protocol_ = value;
}
inline void List::set_protocol(uint64_t value) {
  _internal_set_protocol(value);
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif

}
}

#include <google/protobuf/port_undef.inc>
#endif
