#ifndef GOOGLE_PROTOBUF_INCLUDED_party_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_party_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_party_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}
PROTOBUF_NAMESPACE_CLOSE

struct TableStruct_party_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_party_2eproto;
namespace Proto {
namespace Party {
class Playlist;
struct PlaylistDefaultTypeInternal;
extern PlaylistDefaultTypeInternal _Playlist_default_instance_;
}
}
PROTOBUF_NAMESPACE_OPEN
template<> ::Proto::Party::Playlist* Arena::CreateMaybeMessage<::Proto::Party::Playlist>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Proto {
namespace Party {

class Playlist final :
    public ::PROTOBUF_NAMESPACE_ID::Message  {
 public:
  inline Playlist() : Playlist(nullptr) {}
  ~Playlist() override;
  explicit PROTOBUF_CONSTEXPR Playlist(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Playlist(const Playlist& from);
  Playlist(Playlist&& from) noexcept
    : Playlist() {
    *this = ::std::move(from);
  }

  inline Playlist& operator=(const Playlist& from) {
    CopyFrom(from);
    return *this;
  }
  inline Playlist& operator=(Playlist&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Playlist& default_instance() {
    return *internal_default_instance();
  }
  static inline const Playlist* internal_default_instance() {
    return reinterpret_cast<const Playlist*>(
               &_Playlist_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Playlist& a, Playlist& b) {
    a.Swap(&b);
  }
  inline void Swap(Playlist* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Playlist* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  Playlist* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Playlist>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Playlist& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Playlist& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Playlist* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Proto.Party.Playlist";
  }
  protected:
  explicit Playlist(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  enum : int {
    kBufferFieldNumber = 2,
    kHashFieldNumber = 1,
  };
  void clear_buffer();
  const std::string& buffer() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_buffer(ArgT0&& arg0, ArgT... args);
  std::string* mutable_buffer();
  PROTOBUF_NODISCARD std::string* release_buffer();
  void set_allocated_buffer(std::string* buffer);
  private:
  const std::string& _internal_buffer() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_buffer(const std::string& value);
  std::string* _internal_mutable_buffer();
  public:

  void clear_hash();
  uint32_t hash() const;
  void set_hash(uint32_t value);
  private:
  uint32_t _internal_hash() const;
  void _internal_set_hash(uint32_t value);
  public:

 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr buffer_;
  uint32_t hash_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_party_2eproto;
};


#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

inline void Playlist::clear_hash() {
  hash_ = 0u;
}
inline uint32_t Playlist::_internal_hash() const {
  return hash_;
}
inline uint32_t Playlist::hash() const {
  return _internal_hash();
}
inline void Playlist::_internal_set_hash(uint32_t value) {
  
  hash_ = value;
}
inline void Playlist::set_hash(uint32_t value) {
  _internal_set_hash(value);
}

inline void Playlist::clear_buffer() {
  buffer_.ClearToEmpty();
}
inline const std::string& Playlist::buffer() const {
  return _internal_buffer();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Playlist::set_buffer(ArgT0&& arg0, ArgT... args) {
 
 buffer_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
}
inline std::string* Playlist::mutable_buffer() {
  std::string* _s = _internal_mutable_buffer();
  return _s;
}
inline const std::string& Playlist::_internal_buffer() const {
  return buffer_.Get();
}
inline void Playlist::_internal_set_buffer(const std::string& value) {
  
  buffer_.Set(value, GetArenaForAllocation());
}
inline std::string* Playlist::_internal_mutable_buffer() {
  
  return buffer_.Mutable(GetArenaForAllocation());
}
inline std::string* Playlist::release_buffer() {
  return buffer_.Release();
}
inline void Playlist::set_allocated_buffer(std::string* buffer) {
  if (buffer != nullptr) {
    
  } else {
    
  }
  buffer_.SetAllocated(buffer, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (buffer_.IsDefault()) {
    buffer_.Set("", GetArenaForAllocation());
  }
#endif
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif

}
}

#include <google/protobuf/port_undef.inc>
#endif
